### ISSUE TITLE
Frameworks support

### ISSUE THREAD

**Issue by hekan** [airgram/airgram#1]
Hey, is there way to integrate with Angular?
I installed the package, but during app serve receiving errors:

ERROR in ./node_modules/zlib/lib/zlib.js
Module not found: Error: Can't resolve './zlib_bindings' in 'C:\Users\YMechsheryakov\WebstormProjects\AigramClient\node_modules\zlib\l
ib'
ERROR in ./node_modules/readline/readline.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\YMechsheryakov\WebstormProjects\AigramClient\node_modules\readline'
ERROR in ./node_modules/require-directory/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\YMechsheryakov\WebstormProjects\AigramClient\node_modules\require-directory'
ERROR in ./node_modules/require-directory/index.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\YMechsheryakov\WebstormProjects\AigramClient\node_modules\require-directory
'

**Comment by airgram** [comment]
@hekan Indeed, this version uses the capabilities of server-side JavaScript. Now we are preparing a separate solution for browser.

**Comment by eruslan44** [comment]
> Hey, is there way to integrate with Angular?
> I installed the package, but during app serve receiving errors:
> 
> ERROR in ./node_modules/zlib/lib/zlib.js
> Module not found: Error: Can't resolve './zlib_bindings' in 'C:\Users\YMechsheryakov\WebstormProjects\AigramClient\node_modules\zlib\l
> ib'
> ERROR in ./node_modules/readline/readline.js
> Module not found: Error: Can't resolve 'fs' in 'C:\Users\YMechsheryakov\WebstormProjects\AigramClient\node_modules\readline'
> ERROR in ./node_modules/require-directory/index.js
> Module not found: Error: Can't resolve 'fs' in 'C:\Users\YMechsheryakov\WebstormProjects\AigramClient\node_modules\require-directory'
> ERROR in ./node_modules/require-directory/index.js
> Module not found: Error: Can't resolve 'path' in 'C:\Users\YMechsheryakov\WebstormProjects\AigramClient\node_modules\require-directory
> '

Hi! Did you manage to integrate with angular?
