### ISSUE TITLE
Getting all users in a channel

### ISSUE THREAD

**Issue by MegaITA** [airgram/airgram#100]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

Hello, I would like to know if it's possible to get all users in a channel. I see that it is possible using the getParticipants method: https://docs.madelineproto.xyz/API_docs/methods/channels.getParticipants.html

I tried using getSupergroupMembers but it's limited to 200 users and the offset is just the amount of users skipped in the 200 users array, not in the whole channel.

**Comment by esindger** [comment]
You can't receive more than 200 users of a channel. Please check out [this issue](https://github.com/tdlib/td/issues/679#issuecomment-526661181).

**Comment by frankl1m** [comment]
You have a example for implement with airgram.io? Thanks
