### ISSUE TITLE
Can't import airgram

### ISSUE THREAD

**Issue by HermannKK** [airgram/airgram#102]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ ] `latest`
[ ] `@next`
[x] `^3.0.2` 

**Steps to reproduce or a small repository showing the problem:**

1. Clone the airgam-js-example and install dependencies
`git clone git@github.com:airgram/airgram-js-example.git && cd cd airgram-js-example && npm i`
2. copy the libtdjson.so.1.6.0 file to the root of project
3. modify the .env file 
```
APP_ID="xxxxx"
APP_HASH="xxxx"
TDLIB_COMMAND="./libtdjson.so.1.6.0"
```
4. run with 
`npm run dev`

Error output
```
[nodemon] 1.18.9
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 15939 to restart
[nodemon] watching: ./src/**/*.js
[nodemon] watching extensions: js
[nodemon] starting `node src/index.js`
[nodemon] spawning
[nodemon] child pid: 15952
[nodemon] watching 1 file


#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7fff89fc7f70
 1: 0xa95a01  [node]
 2: 0x19617d4 V8_Fatal(char const*, ...) [node]
 3: 0xe58149 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xbc5418 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0xa08589 node::Buffer::New(node::Environment*, char*, unsigned long, void (*)(char*, void*), void*) [node]
 6: 0xa089f3 node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [node]
 7: 0x9fdbdd napi_create_external_buffer [node]
 8: 0x7fda204ff4d8  [/home/kaoh/Documents/telegram-scrapper/airgram-js-example/node_modules/ffi-napi/build/Release/ffi_bindings.node]
 9: 0x7fda205023c7 FFI::FFI::InitializeBindings(Napi::Env, Napi::Object) [/home/kaoh/Documents/telegram-scrapper/airgram-js-example/node_modules/ffi-napi/build/Release/ffi_bindings.node]
10: 0x7fda205029c1  [/home/kaoh/Documents/telegram-scrapper/airgram-js-example/node_modules/ffi-napi/build/Release/ffi_bindings.node]
11: 0x7fda204ff595 __napi_Init(napi_env__*, napi_value__*) [/home/kaoh/Documents/telegram-scrapper/airgram-js-example/node_modules/ffi-napi/build/Release/ffi_bindings.node]
12: 0x9fcc58 napi_module_register_by_symbol(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, napi_value__* (*)(napi_env__*, napi_value__*)) [node]
13: 0xa00b14  [node]
14: 0x9ffebd node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [node]
15: 0xc0278b  [node]
16: 0xc03d36  [node]
17: 0xc043b6 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
18: 0x13a5b79  [node]
Illegal instruction
```
**What i've done**

1. changing libtdjson file path in .env file from relative path to absolute path
2. Removed airgram line from package.json and deleted package-lock.json then reinstalled with npm
3. Commented all the code and leaving only the import line with only 
`const { Airgram } = require('airgram')`
and i figured out the source of the error and i need help to solve it

**System informations**
- node version: 14.2.0
- OS: kali 2020.1
- npm version: 6.14.5
- node-gyp: v6.1.0

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] question
    [ ] bug report

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by jumoog** [comment]
you can't use 14.x right now

**Comment by HermannKK** [comment]
Thanks for your answer
so which version can i use?

**Comment by esindger** [comment]
It works with Node.JS v12 for me.

**Comment by HermannKK** [comment]
> It works with Node.JS v12 for me.
Thanks tested and worked for me

**Comment by T1MOXA** [comment]
https://github.com/node-ffi-napi/node-ffi-napi/commit/646ee5ba4bb70b3ee978cf655f8d4fbe67f388fc

**Comment by jumoog** [comment]
with the new release you can use V14 now
