### ISSUE TITLE
Chat not found when sending message

### ISSUE THREAD

**Issue by MegaITA** [airgram/airgram#103]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hello, I have a bot which gets an array of userIDs from a group of friends, then when I want to send an announcement i iterate over an array of those userIDs and i send the message to everyone of them. I'm the only one who gets the message, for the other ones I get the error code 5: "chat not found". By the way they sent messages to the userbot...

Here's the code:
`    for(let member of members) {

      console.log(`Sending message to: ${member.userId}`);

      let mess = await airgram.api.sendMessage({
        chatId: member.userId,
        replyToMessageId: 0,
        inputMessageContent: {
          _: "inputMessageText",
          text: {
            _: "formattedText",
            text: announcement
          },
        }
      });

      console.log(mess);

    }`

That's the console output:

`Sending message to: 799304918
{
  airgram: [Getter],
  getState: [Function: getState],
  setState: [Function: setState],
  _: 'sendMessage',
  options: {},
  request: {
    method: 'sendMessage',
    params: {
      chatId: 799304918,
      replyToMessageId: 0,
      inputMessageContent: [Object]
    }
  },
  response: { _: 'error', code: 5, message: 'Chat not found' }
}`
`Sending message to: 161936319
{
  airgram: [Getter],
  getState: [Function: getState],
  setState: [Function: setState],
  _: 'sendMessage',
  options: {},
  request: {
    method: 'sendMessage',
    params: {
      chatId: 161936319,
      replyToMessageId: 0,
      inputMessageContent: [Object]
    }
  },
  response: {
    _: 'message',
    id: 650117121,
    senderUserId: 943185478,
    chatId: 161936319,
    sendingState: { _: 'messageSendingStatePending' },
    isOutgoing: true,
    canBeEdited: false,
    canBeForwarded: true,
    canBeDeletedOnlyForSelf: false,
    canBeDeletedForAllUsers: true,
    isChannelPost: false,
    containsUnreadMention: false,
    date: 1589746682,
    editDate: 0,
    replyToMessageId: 0,
    ttl: 0,
    ttlExpiresIn: 0,
    viaBotUserId: 0,
    authorSignature: '',
    views: 0,
    mediaAlbumId: '0',
    restrictionReason: '',
    content: { _: 'messageText', text: [Object] }
  }
}`

**Comment by esindger** [comment]
You need to call `getChat()` before `sendMessage()`. 
Related issue: https://github.com/tdlib/td/issues/837

**Comment by MegaITA** [comment]
> You need to call `getChat()` before `sendMessage()`.
> Related issue: [tdlib/td#837](https://github.com/tdlib/td/issues/837)

Thanks, I'll try that out!

**Comment by MegaITA** [comment]
> You need to call `getChat()` before `sendMessage()`.
> Related issue: [tdlib/td#837](https://github.com/tdlib/td/issues/837)

I tried that out but I still get 'Chat not found' error... but if I use getUser() it gets him correctly. By the way, the userId and chatId are the same, I have no clue why it's returning me this error.

**Comment by MegaITA** [comment]
Okay solved, for the currently opened chats just use getChats(), if you have to send a message to a new user that have never contacted you before you have just to check if the response code of sendMessage() is equal to 5, that means that it didn't find a chat with the given chatId, if that is true you have just to call createPrivateChat() and then again sendMessage(). Hope it will be helpful for other people which will have my problems.
