### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by mitGen** [airgram/airgram#107]
**Issue type:**
Hello!!!
Tell me how I can create a separate function so that I can authorize by passing the necessary parameters like this:
![image](https://user-images.githubusercontent.com/44039203/82905295-5cc63780-9f6c-11ea-941c-988c6cd9fa23.png)
but for some reason it doesn’t work ....... It only works when this method is outside the function!!!
??????How can I log in if I want to do this a separate route in my application???????
**Airgram version:**
[ ] `latest`
[ ] `@next`
[ ] `3.0.2` (or put your version here)

**Comment by esindger** [comment]
Middleware `Auth` have to be installed only once after initializing the Airgram instance. Do not put `airgram.use()` inside a function. See is an [example](https://airgram.io/guides/basic-concepts/authorization#sign-in-as-a-user).

> I want to do this a separate route in my application

If you want to authorize user when some event occured, you need to create a new instance of Airgram. Something like this:

```ts
function factory(config) {
  const airgram = new Airgram(config)

  airgram.use(new Auth({
    // auth middleware config
  }))

  return airgram
}
```

**Comment by mitGen** [comment]
Thanks!!!!!
