### ISSUE TITLE
error message not found

### ISSUE THREAD

**Issue by eringiso** [airgram/airgram#108]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ x] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi i'm getting an error while editing the message

i have two channels one main and one test whenever i send a message in main channel from app
i run a checkMessage function inside updateNewMessage and the function returns some result which is appended to the message so it works fine and edits the message without any error

but i get error when the message is sent programatically here i send the message to main channel when i get a message from the test channel and both are private channels

the function checkMessage runs for both the channels when new
message is received  in any of them

if i receive a message from test channel the checkMessage runs and sends message to the main channel only if result is true and chatId is of test channel and then again checkMessage runs for the main channel message but here i get error when editing the message saying

response: { _: 'error', code: 5, message: 'Message not found' }

```
  async function checkMessage(webId,chatId) {


    let mId = ""
    let param=""

    return new Promise((res, rej) => {
      let result = ""
      // api is websocket connection which returns data after checking the message

      api.events.on('x', async function(response) {

        if (true) {
        	result = data
          try {
            res([mId,param, result])
          } catch (e) {
            return new Promise
          }


        }
      })
      api.subscribe(webId)

    }).then(
      async (x) => {
        let [id, param, result] = x
        if(result === "true" && chatId === test ){
          let text = sometext
          let m = await sendMessage(main, text)

        }

      await airgram.api.getChats({
        limit: 10,
        offsetChatId: 0,
        offsetOrder: '9223372036854775807'
      })

        let finalResult = await editMessage(id, chatId, result)
        console.log(finalResult);

        return x
      })


  }

```

the response i get when the message is sent programatically

```

{
  airgram: [Getter],
  getState: [Function: getState],
  setState: [Function: setState],
  _: 'editMessageText',
  options: {},
  request: {
    method: 'editMessageText',
    params: {
      chatId: main,
      messageId: id,
      canBeEdited: true,
      inputMessageContent: [Object]
    }
  },
  response: { _: 'error', code: 5, message: 'Message not found' }
}

```

the response i get when the message is sent from the app in main channel

```

{
  airgram: [Getter],
  getState: [Function: getState],
  setState: [Function: setState],
  _: 'editMessageText',
  options: {},
  request: {
    method: 'editMessageText',
    params: {
      chatId: main,
      messageId: id,
      canBeEdited: true,
      inputMessageContent: [Object]
    }
  },
  response: {
    _: 'message',
    id: id,
    senderUserId: 0,
    chatId: main,
    isOutgoing: true,
    canBeEdited: true,
    canBeForwarded: true,
    canBeDeletedOnlyForSelf: false,
    canBeDeletedForAllUsers: true,
    isChannelPost: true,
    containsUnreadMention: false,
    date: 1591017263,
    editDate: 1591017362,
    replyToMessageId: 0,
    ttl: 0,
    ttlExpiresIn: 0,
    viaBotUserId: 0,
    authorSignature: '',
    views: 1,
    mediaAlbumId: '0',
    restrictionReason: '',
    content: { _: 'messageText', text: [Object] }
  }
}



```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] question
    [ ] bug report

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by esindger** [comment]
Sorry, I am not sure that I understand what you want to do. 

Are you sure you have permanent message id? When you send new message TDLib returns temporary message id and then you need to receive permanent one by the `updateNewMessage` update.

**Comment by eringiso** [comment]
Hi yes i have the permanent message id  i'm using this helper function
https://github.com/airgram/airgram/issues/99#issuecomment-629559071
what i want to achieve is to append some text to the message when i receive the message from the main channel it works fine when the message is sent from the app but i get error when i send message programmatically

**Comment by eringiso** [comment]
I've observed something strange here
the messageId that i'm getting from sendMessage helper function https://github.com/airgram/airgram/issues/99#issuecomment-629559071 is  66060288 which is permanent messageId but i'm not storing this id because i thought i could capture it in updateNewMessage
but here i get different messageId 65011713  and i'm storing this id 

when i use editMessage with 65011713 i get the error message not found
