### ISSUE TITLE
How to provide additional arguments to Store constructor (InversifyJS) ?

### ISSUE THREAD

**Issue by volodalexey** [airgram/airgram#11]
At [runtime](https://github.com/volodalexey/airgram-user-and-bot-test/blob/master/src/test.ts#L20) I need to have two different stores. One for Bot and Another one for User.
Right now I am using two different stores for two instances, [first](https://github.com/volodalexey/airgram-user-and-bot-test/blob/master/src/bot.store.ts) and [second](https://github.com/volodalexey/airgram-user-and-bot-test/blob/master/src/user.store.ts).
However this ducplicates the code. What I need Is to provide some unique [String to Store](https://github.com/volodalexey/airgram-user-and-bot-test/blob/master/src/user.store.ts#L6).
I think the same problem will be with another store implementation, e.g. provide two different connection strings for DB (for Bot and for User).
I assume that this problem can be solved with [Inversify Factory](https://github.com/inversify/InversifyJS/blob/master/wiki/factory_injection.md).
But I do not control store container invocation. In your example you will also have [code duplication](https://github.com/airgram/airgram/blob/master/examples/pouchdb-store/PouchDBStore.ts#L5) in case of two Stores, right?
Is it possible to provide some unique string to Store class?

**Comment by airgram** [comment]
You may use [activation handler](https://github.com/inversify/InversifyJS/blob/master/wiki/activation_handler.md) to pass some parameters to the class.
```
airgram.bind<JSONStore<ag.MtpState>>(TYPES.MtpStateStore).to(JSONStore)
  .onActivation((context, store) => {
    store.storePath = '/path/to/store.json'
    return store
  })
```

**Comment by volodalexey** [comment]
Awesome! Thanks.
