### ISSUE TITLE
How to use airgram.catch to rewrite errors handling?

### ISSUE THREAD

**Issue by safead** [airgram/airgram#110]
**Issue type:**

[ X] question

**Airgram version:**

[X ] `latest`

**Steps to reproduce or a small repository showing the problem:**

Please advise, how can I control all the global error messages (or catch all of them additionally in callbacks), my code:
```
      const instance = new Airgram({
        ...
      });
      instance.catch(error => {
        console.log('NEVER INVOKED'); // I need to get all the airgram system errors like:
// [ 2][t 2][1592408997.257074118][FileManager.cpp:3483][#1][!FileManager] Failed to Download file 24143(0) of type photos: [WindowsError
      });
```

**Comment by esindger** [comment]
Hello,
the `catch` method is intended for handling of runtime errors. If you need to catch TDLib errors you can add a middleware to the beginning of the middlewares chain:

```ts
import { Airgram, isError } from 'airgram'

const airgram = new Airgram({
  // config
})

// catch errors
airgram.use(async (ctx, next) => {
  const promise = await next() // wait for response
  if ('request' in ctx && isError(ctx.response)) {
    console.info(`Error ${ctx.response.code}: ${ctx.response.message}`);
  }
  return promise
})

// ... other middleware
```

**Comment by safead** [comment]
Thanks a lot for the solution and a great job. Please support this lib in future.
PS. Fix ContactInput[] type in the docs ;)

**Comment by safead** [comment]
> Hello,
> the `catch` method is intended for handling of runtime errors. If you need to catch TDLib errors you can add a middleware to the beginning of the middlewares chain:
> 
> ```ts
> import { Airgram, isError } from 'airgram'
> 
> const airgram = new Airgram({
>   // config
> })
> 
> // catch errors
> airgram.use(async (ctx, next) => {
>   const promise = await next() // wait for response
>   if ('request' in ctx && isError(ctx.response)) {
>     console.info(`Error ${ctx.response.code}: ${ctx.response.message}`);
>   }
>   return promise
> })
> 
> // ... other middleware
> ```

the condition
```if ('request' in ctx && isError(ctx.response))```
is never performed. Please assist...

**Comment by esindger** [comment]
Sorry for long reply.
I've just checked it up, everything is working for me. 
```ts
    const airgram = new Airgram({
      // config
    })

    airgram.use(new Auth({
      // config
    }))

    airgram.use(async (ctx, next) => {
      await next()
      if ('request' in ctx && isError(ctx.response)) {
        console.info(`Error ${ctx.response.code}: ${ctx.response.message}, request ${JSON.stringify(ctx.request)}`);
      }
    })

    const chatResponse = await airgram.api.getChat({
      chatId: 1
    })
```

Output:
```
Error 6: Chat not found, request {"method":"getChat","params":{"chatId":1}}
```

Please check whither all you middlewares call `await next()` or not. If you do not call `next` function, the next middleware will not run.

**Comment by esindger** [comment]
> Setting up a proxy before auth stage always break the login process (Win10, tdlib compiled locally). It will be very helpful to fix this issue.

Now proxy methods are available before authorization.

**Comment by safead** [comment]
> Sorry for long reply.
> I've just checked it up, everything is working for me.
> 
> ```ts
>     const airgram = new Airgram({
>       // config
>     })
> 
>     airgram.use(new Auth({
>       // config
>     }))
> 
>     airgram.use(async (ctx, next) => {
>       await next()
>       if ('request' in ctx && isError(ctx.response)) {
>         console.info(`Error ${ctx.response.code}: ${ctx.response.message}, request ${JSON.stringify(ctx.request)}`);
>       }
>     })
> 
>     const chatResponse = await airgram.api.getChat({
>       chatId: 1
>     })
> ```
> 
> Output:
> 
> ```
> Error 6: Chat not found, request {"method":"getChat","params":{"chatId":1}}
> ```
> 
> Please check whither all you middlewares call `await next()` or not. If you do not call `next` function, the next middleware will not run.

I think we are talking about different types of errors. I need to catch & analize all the internal tdlib errors, like

```
[ 2][t 5][1593550932.854186058][NetQueryDelayer.cpp:82][#1][!NetQueryDelayer]   Delay: [Query:[id:56098816][tl:0xca30a5b1][state:Query]] [timeout:4.000000][total_timeout:4.000000] because of [Error : 420 : FLOOD_WAIT_4] from Session:2:main::Connect::Tcp::
```

But this method (using middleware) does not working in this case. Any other ideas?

**Comment by esindger** [comment]
Airgram does not have access to the TDLib internal logs. However, you can use [`setLogStream`](https://airgram.io/api-reference/api-methods/setLogStream) method to save logs to a file.

**Comment by safead** [comment]
Got it.

#close
