### ISSUE TITLE
Missing `contacts.resolveUsername`

### ISSUE THREAD

**Issue by AndrewLaneX** [airgram/airgram#111]
**Issue type:**

- [ ] question
- [x] bug report
- [ ] feature request
- [ ] documentation issue

**Airgram version:**

- [x] `latest`
- [ ] `@next`
- [ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

[`contacts.resolveUsername`](https://github.com/tdlib/td/blob/f45d80fe16f99d112d545b7cd74ce46342fe3437/td/generate/scheme/telegram_api.tl#L1236) used to be in [v0.1.x](https://github.com/airgram/airgram/blob/5ca8e379c85d447788b6b22fc3e8a99d50b97e3e/src/api/methods/contacts.ts#L138-L139) but seems to be missing in the v3.

**Comment by AndrewLaneX** [comment]
Duplicate of #

**Comment by AndrewLaneX** [comment]
Oops. :laughing:

**Comment by esindger** [comment]
Hello, 
Airgram uses [td_api.tl](https://github.com/tdlib/td/blob/f45d80fe16f99d112d545b7cd74ce46342fe3437/td/generate/scheme/td_api.tl) scheme.

**Comment by AndrewLaneX** [comment]
Is there a different way to resolve usernames?

**Comment by esindger** [comment]
Please check out [`checkChatUsername`](https://airgram.io/api-reference/api-methods/checkChatUsername).

**Comment by esindger** [comment]
Probably you can get more info [here](https://github.com/tdlib/td/issues/99).

**Comment by AndrewLaneX** [comment]
I'm trying to get the user or chat with that username, not check if the username is available.

**Comment by esindger** [comment]
So you need to use [`searchPublicChat`](https://airgram.io/api-reference/api-methods/searchPublicChat). This is the [same](https://github.com/tdlib/td/issues/99#issuecomment-368480265) as `contacts.resolveUsername`.

**Comment by AndrewLaneX** [comment]
Cool, thanks!
