### ISSUE TITLE
GET request blocks auth

### ISSUE THREAD

**Issue by GABASTAR** [airgram/airgram#113]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I wanted to make automatic registrator, that will take number and sms from site by using GET request via axios, but after first GET request, I cant sign up because auth stops working, also if I set phoneNumber: null, Airgram will not throw an error, but when I commenting axios GET request it starts to work as normal
Here is an example of my code:
```js 
async function getNumber () {
    const response = await axios({
        url: "http://sitewithphonenumber.com,
        method: "GET"
    })
    return response.data
}
void (async function () {
        let response = await getNumber()
        let phoneNumber = response.number
        airgram.use(new Auth({
            phoneNumber: phoneNumber
         }))
})()
```
Also using prompt("Enter phone number here: ") will not throw text "Enter phone number here: " in console and will not work with GET request

**Comment by esindger** [comment]
The Auth middleware should be set once just after creating of Airgram instance. Asynchronous adding won't work correctly because middleware will miss a number of updates from Telegram. 

You can pass `getNumber` function as the `phoneNumber` option value:

```ts
void (async function () {
  airgram.use(new Auth({
    phoneNumber: getNumber
  }))
})()
```

**Comment by GABASTAR** [comment]
Thanks a lot for your comment, but this solution:
```js
void (async function () {
  airgram.use(new Auth({
    phoneNumber: getNumber
  }))
})()
```
will throw an error ```[Airgram Auth] quit due an error: "phoneNumber.trim is not a function"``` for me

So I solved problem with phoneNumber by creating Airgram instance near to Auth, but there is another problem that I dont know how to get a code, because after filling phoneNumber, code will not be sent to phone number and also as I know, I cant do thing like this:
```js
async function getNumber () {
    const response = await axios({
        url: "http://sitewithphonenumber.com,
        method: "GET"
    })
    return response.data
}
async function getCode () {
    const response = await axios({
        url: "http://sitewithphonenumber.com,
        method: "GET"
    })
    return response.data
}
void (async function () {
        let responseNumber = await getNumber()
        let phoneNumber = responseNumber.number
        const airgram = new Airgram({
        ...
        })
        airgram.use(new Auth({
            phoneNumber: phoneNumber
        }))
        let responseCode = await getCode()
        let code = responseCode.code
        airgram.use(new Auth({
            code: code,
            firstName: "firstName",
            secondName: "secondName"
        }))
})()
```
because Auth should be full:
```js
airgram.use(new Auth({
  phoneNumber: phoneNumber,
  code: code,
  firstName: "firstName",
  secondName: "secondName"
}))
```

**Comment by esindger** [comment]
> will throw an error [Airgram Auth] quit due an error: "phoneNumber.trim is not a function" for me

Be ensure that the `getNumber` returns string (not a number).

This code should work:
```ts
function airgramFactory () {
  const airgram = new Airgram({
    // config
  })
  
  let phoneNumber = null

  airgram.use(new Auth({
    phoneNumber: async () => {
      const response = await getPhone()
      phoneNumber = response.number
      return String(response.number)
    },
    code: async () => {
      const response = await getCode(phoneNumber)
      return String(response.code)
    }
  }))
  
  return airgram
}
```

**Comment by GABASTAR** [comment]
Thank you so much, it works for me
