### ISSUE TITLE
pls add Folder feature in airgram

### ISSUE THREAD

**Issue by domingogogo** [airgram/airgram#115]
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Airgram version:**

[x ] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hi guy. I saw the TDlib-web was updated to 1.6.6 and the telegram-web has folder feature in chat. pls update and add that feature.
thank you so much.

**Comment by esindger** [comment]
Airgram has been updated to TDLib v1.6.6.

**Comment by domingogogo** [comment]
thank you so much. have a good day.
