### ISSUE TITLE
TypeError: Cannot redefine property: Airgram

### ISSUE THREAD

**Issue by ajai06** [airgram/airgram#116]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ ] `latest`
[ ] `@next`
[x ] `3.1.0` (or put your version here);

i tired to import "airgram/web" in react app, but i got error like this

TypeError: Cannot redefine property: Airgram
./node_modules/@airgram/web/index.js

**Comment by esindger** [comment]
Can you create a simple repository which shows how to reproduce this error?

**Comment by ajai06** [comment]
yeah sure.
checkout this https://github.com/ajai06/airgram-web-react.git
