### ISSUE TITLE
how to disable logs?

### ISSUE THREAD

**Issue by dave-dm** [airgram/airgram#122]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ ] `latest`
[ ] `@next`
[x ] `3.1.1` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am getting crazy logs starting with `[ 3][t 4]`.

I tried setting

```
const airgram = new Airgram({
  logVerbosityLevel: 1
})

const airgram = new Airgram({
  logVerbosityLevel: 0
})

const airgram = new Airgram({
  logVerbosityLevel: 9
})
```
nothing works. I don't want to get any log whatsoever.

**Comment by jumoog** [comment]
with `logVerbosityLevel: 0` you only get 2 logoutputs at the start

**Comment by dave-dm** [comment]
> with `logVerbosityLevel: 0` you only get 2 logoutputs at the start

not me, I get hundreds of lines of logs constantly all starting with `[ 3][t 4]` or similar . I'm using this binary https://github.com/Bannerets/tdlib-binaries/blob/master/1.2.0/linux64/libtdjson.so

**Comment by dave-dm** [comment]
I made a test repo if someone wants to try to reproduce https://github.com/dave-dm/airgram-test

**Comment by esindger** [comment]
> I'm using this binary https://github.com/Bannerets/tdlib-binaries/blob/master/1.2.0/linux64/libtdjson.so

This is TDLib `1.2.0` but the `setLogVerbosityLevel` method has been added in version `1.4.0`. Please use the latest version of TDLib.

**Comment by dave-dm** [comment]
> > I'm using this binary https://github.com/Bannerets/tdlib-binaries/blob/master/1.2.0/linux64/libtdjson.so
> 
> This is TDLib `1.2.0` but the `setLogVerbosityLevel` method has been added in version `1.4.0`. Please use the latest version of TDLib.

that fixed the problem thanks
