### ISSUE TITLE
Receiving messages upon client startup.

### ISSUE THREAD

**Issue by jagzmz** [airgram/airgram#123]
**Issue type:**

- [x] question

**Airgram version:**

- [x] `latest`

When I have received/sent some messages on telegram when the airgram client is stopped, upon starting I receive events of those messages.

I can ignore them comparing with current time and message time, but I need to know why this happens and if there is any option to disable it.

Thank You

**Comment by esindger** [comment]
Hello,
I believe your question is related to TDLib, not Airgram. Please can you open a new issue [here](https://github.com/tdlib/td/issues)?

**Comment by jagzmz** [comment]
> Hello,
> I believe your question is related to TDLib, not Airgram. Please can you open a new issue [here](https://github.com/tdlib/td/issues)?

Oke will do!

Another thing, does tdlib/airgram provides a way to know the content of the message which was edited when updateMessageContent or updateMessageEdited is triggered, or I have to maintain message database at my end ?
