### ISSUE TITLE
How to login after a logout?

### ISSUE THREAD

**Issue by jagzmz** [airgram/airgram#127]
**Issue type:**

- [x] question

**Airgram version:**

- [x] latest

After doing a `api.logOut()`, authorizationState is changed to `authorizationStateClosed`.

How can I reopen the autorizationState without doing a node process restart?

Do I have to create a new airgram instance on the fly after the previous one is logged out?

**Comment by jagzmz** [comment]
So I have solved it by creating a new airgram instance again.
Is there any way to renew/re-login the existing instance?

**Comment by esindger** [comment]
Hello,
you need to create a new Airgram instance after logout. Re-login means to create new TDLib instance and Airgram is just a wrapper on it.

**Comment by jagzmz** [comment]
Ok. Thanks
