### ISSUE TITLE
Airgram has memory leak when polling enabled?

### ISSUE THREAD

**Issue by volodalexey** [airgram/airgram#13]
If I start updates in JEST test:
```
describe("Check", () => {
  const testConfig = createTestAppConfig();
  let airgram: Airgram;

  beforeAll(async () => {
    const airgram = new Airgram(testConfig.api_id, testConfig.api_hash);
    const { updates } = airgram;
    airgram.use(updates);
    await updates.startPolling();
  });

  it("check", async () => {
    await new Promise((resolve) => {
      setTimeout(resolve, 2000)
    })
    expect(true).toBe(true);
  })

  afterAll(async () => {
    await airgram.updates.stop();
    await airgram.destroy()
  })
});
```
After test JEST shows me that something is running:
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
If I comment out this `airgram.updates.startPolling()` - everything is ok.
If I run `airgram.updates.stop()` - does not work.
If I run `airgram.destroy()` - does not work.
Am I missing something, to destroy airgram?

**Comment by esindger** [comment]
Destroy function has been fixed. Please check it in your environment. If the problem persists, create a simple repository to reproduce it.

**Comment by esindger** [comment]
> Airgram has memory leak when polling enabled

I tested active long polling connection during few days. Memory hasn't increased.

**Comment by volodalexey** [comment]
Tested with version 0.1.12. Now Jest ends test correctly. It works. Thanks!
