### ISSUE TITLE
Version compatibility (new TDLib JSON interface)

### ISSUE THREAD

**Issue by esindger** [airgram/airgram#130]
Airgram `3.2.*` is implementing [new TDLib JSON interface](https://github.com/tdlib/td/blob/966621376b87fda5b9eb29dd2f4da7732bf1c654/td/telegram/td_json_client.h#L97-L158). It required TDLib `v 1.6.9` or higher, which you have to build from the `HEAD` of `master` branch. For using previous version of TDLib you need to set in `package.json` exact version of Airgram:
* TDLib 1.6.6 - `"airgram": "3.1.1"`
* TDLib 1.6.0 - `"airgram": "3.0.2"`

**Comment by mccoysc** [comment]
@esindger i installed the `"airgram": "3.0.2"` but it still use the new td interface.
![image](https://user-images.githubusercontent.com/18025276/97833936-894b6000-1d11-11eb-8b1b-2ccb3ecf39aa.png)
￼￼
![image](https://user-images.githubusercontent.com/18025276/97833988-ab44e280-1d11-11eb-94f1-8e8b9f79cd71.png)

**Comment by mccoysc** [comment]
still error for `"airgram": "3.0.2"` and tdlib 1.6.0:
![image](https://user-images.githubusercontent.com/18025276/97836052-68393e00-1d16-11eb-814b-7cfd3f8567a4.png)

**Comment by mccoysc** [comment]
![image](https://user-images.githubusercontent.com/18025276/97836720-de8a7000-1d17-11eb-9cb0-5fe15dda9416.png)

**Comment by mccoysc** [comment]
and also,maybe,you need give a pre-build tdjson binaries for current airgram,include native and wasm.
for the tdlib need so many dependcies and not so easy for compile

**Comment by esindger** [comment]
@mccoysc Can you provide an example of code to reproduce this error?

**Comment by mccoysc** [comment]
the code is from github example code in README



发自我的iPhone


------------------ Original ------------------

**Comment by jumoog** [comment]
the example is outdated anyways..
since https://github.com/airgram/airgram/commit/60d1ea6f4d24f5f11fbcaa8e1dcf92048800c48c
i had to create my own tdJsonClient
```JS
const tdJsonClient = new TdJsonClient({
  command: resolvePath('libtdjson'),
});
```
```JS
const airgram = new Airgram(tdJsonClient, {
  apiId: process.env.APIID as number | undefined,
  apiHash: process.env.APIHASH,
  logVerbosityLevel: 0,
  enableStorageOptimizer: true,
});
```

otherwise i got the error message `For using models you need to create TdJsonClient manually. See: https://airgram.netlify.app/api-reference/tdjsonclient`

**Comment by esindger** [comment]
The `models` option is no longer supported for Airgram instances. Internally, the library uses a single `TDLibJsonClient` to resolve [this issue](https://github.com/airgram/airgram/issues/114). As a result, you may encounter the problem of model inconsistency if you pass different models to different Airgram instances. To avoid this, you need explicitly pass the models to `TDLibJsonClient`.

```ts

const tdJsonClient = new TdJsonClient({
  command: resolvePath('libtdjson'),
  models: {
    chat: ChatModel
  }
});

const airgram1 = new Airgram(tdJsonClient, {
  // options
});

const airgram2 = new Airgram(tdJsonClient, {
  // options
});
```

**Comment by mccoysc** [comment]
@esindger but what reason for my error?

**Comment by mccoysc** [comment]
![image](https://user-images.githubusercontent.com/18025276/97936069-66728780-1db5-11eb-9b7a-d0d2e996d66c.png)
error at this line like the above.

**Comment by esindger** [comment]
> ![image](https://user-images.githubusercontent.com/18025276/97936069-66728780-1db5-11eb-9b7a-d0d2e996d66c.png)
> error at this line like the above.

Can you please create a small repository to reproduce this error?

**Comment by jumoog** [comment]
if you use the current master with commit https://github.com/tdlib/td/commit/6a9cd7263680b2f73424cdf4611f1082c1c78174 you have start the client by sending request. In their example they use:
```JSON
{"@type":"getOption", "name":"version"}
```

old code example:
```JS
const airgram = new Airgram(tdJsonClient, {
  apiId: process.env.APIID as number | undefined,
  apiHash: process.env.APIHASH,
});

airgram.use(new Auth({
  token: process.env.BOT_TOKEN,
}));
```

example request code
```JS
airgram.provider.send({ method: 'getOption', params: { name: 'version' } });
```

new code example:
```JS
const airgram = new Airgram(tdJsonClient, {
  apiId: process.env.APIID as number | undefined,
  apiHash: process.env.APIHASH,
});

airgram.use(new Auth({
  token: process.env.BOT_TOKEN,
}));

airgram.provider.send({ method: 'getOption', params: { name: 'version' } });
```

**Comment by TrueCarry** [comment]
@mccoysc, not sure if problem still exists, but it turned out problem was in @airgram/core package. It got updated for new api and 3.0.1 trying to use core@3.2.x. I fixed it by making custom resolution in package.json, but not sure yet if everything works.
```
  "resolutions": {
	"dependencies": {
		"airgram": "3.0"
	},
	"airgram/@airgram/core": "~3.0.0"
  }
```

@esindger is it possible to release airgram@3.0.3 and @3.1.2 with ~ instead of ^ in dependencies?

**Comment by esindger** [comment]
> @esindger is it possible to release airgram@3.0.3 and @3.1.2 with ~ instead of ^ in dependencies?

Done.

**Comment by esindger** [comment]
Since today only releases based on the stable version of TDLib (like 1.6 or upcoming 1.7) will be marked by the `latest` tag. All other releases will have a tag with appropriate TDLib version.

So, to install a version compatible with TDLib 1.6.10, you need to use the command: `npm install airgram@tdlib-1.6.10`

**Comment by bodrych** [comment]
@esindger when 1.7? :)

**Comment by esindger** [comment]
Released.
