### ISSUE TITLE
example for inputFileGenerated

### ISSUE THREAD

**Issue by jumoog** [airgram/airgram#131]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

how to use "inputFileGenerated"? According to the documentation you have to implement the generation yourself.

**Comment by esindger** [comment]
Have you read [this thread](https://github.com/tdlib/td/issues/126)? You can find there some information about how it works.
