### ISSUE TITLE
api search has airgram.io links

### ISSUE THREAD

**Issue by jumoog** [airgram/airgram#133]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

using the search at https://airgram.netlify.app/ shows results with airgram.io links

**Comment by jumoog** [comment]
all results still point to airgram.io
![grafik](https://user-images.githubusercontent.com/5268791/99879926-5f020980-2c10-11eb-92bd-bed381ada096.png)

**Comment by esindger** [comment]
I've sent a request to Algolia DocSearch and waiting for response.
