### ISSUE TITLE
The "command" option must have the same value as in active TdJsonClient instance.

### ISSUE THREAD

**Issue by uWynell** [airgram/airgram#135]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[X] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

No steps, it's works for me, that's all

**Issue itself:**
![image](https://user-images.githubusercontent.com/65278392/98930389-a0e2cf80-24ed-11eb-9d09-502be672d329.png)

**Code:**
```ts
import { Airgram, Auth, prompt, toObject } from 'airgram'

const airgram = new Airgram({
  apiId: process.env.APP_ID,
  apiHash: process.env.APP_HASH,
  command: ''
})

airgram.use(new Auth({
  code: () => prompt(`Please enter the secret code:\n`),
  phoneNumber: () => prompt(`Please enter your phone number:\n`)
}))

void (async () => {
  const me = toObject(await airgram.api.getMe())
  console.log(`[me]`, me)
})

// Getting all updates
airgram.use((ctx, next) => {
  if ('update' in ctx) {
    console.log(`[all updates][${ctx._}]`, JSON.stringify(ctx.update))
  }
  return next()
})

// Getting new messages
airgram.on('updateNewMessage', async ({ update }, next) => {
  const { message } = update
  console.log('[new message]', message)
  return next()
})
```

**Directory state:**
![image](https://user-images.githubusercontent.com/65278392/98930510-ccfe5080-24ed-11eb-8608-2dd9f8b0357c.png)

**Comment by jumoog** [comment]
https://github.com/airgram/airgram/issues/130#issuecomment-720355464

**Comment by jumoog** [comment]
you have to create your own TdJsonClient. 

for Windows its `tdjson` for Linux `libtdjson`

```JS
import { resolve as resolvePath } from 'path';

const tdJsonClient = new TdJsonClient({
  command: resolvePath('libtdjson'),
});

const airgram = new Airgram(tdJsonClient, {
//...
});
```

**Comment by esindger** [comment]
@uWynell, I found out why you are facing this error. It will be fixed in the next release. Please temporary use a workaround as adviced @jumoog

**Comment by uWynell** [comment]
> @uWynell, I found out why you are facing this error. It will be fixed in the next release. Please temporary use a workaround as adviced @jumoog
ye I did that and it worked, thanks
