### ISSUE TITLE
Chat not found with correct chat id

### ISSUE THREAD

**Issue by vladshcherbin** [airgram/airgram#136]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[x] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

Hey 👋 

If I use `getChat` with correct chat id from start, it returns:

```js
response: { _: 'error', code: 6, message: 'Chat not found' }
```

However, if I call `getChats` and then `getChat` with same id, it returns chat correctly.

Any idea why `getChat` doesn't work from start, is it some limitation of `tdlib` or `airgram`?
Maybe some link to read about.

**Comment by jumoog** [comment]
If you can use the function `getChats` you are not using the API as a bot. According to the TDLib documentation `getChat` is used offline if the user is not a bot. But to know the chats offline you have to call `getChats` first. Only bots can use `getChat` directly without any additional steps. https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chat.html

**Comment by vladshcherbin** [comment]
@jumoog thank you a lot! ❤️
