### ISSUE TITLE
TDLib 1.7 support?

### ISSUE THREAD

**Issue by nikolaygit** [airgram/airgram#142]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`

**Question:**

Is TDLib 1.7 supported in the latest airgram version? If not where can I follow when it will become supported?

**Comment by jumoog** [comment]
> Is TDLib 1.7 supported in the latest airgram version? If not where can I follow when it will become supported?

yes

**Comment by nikolaygit** [comment]
thanks!
