### ISSUE TITLE
example for 429 middleware

### ISSUE THREAD

**Issue by jumoog** [airgram/airgram#143]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ ] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

i keep getting 429 errors. I am looking for a way to interrupt the dispatch in this case for the specified time and then process the messages that have occurred. Is it possible to timeout the execution of next()? or does tdlib stop working at some point?

**Comment by esindger** [comment]
You can delay requests by using a middleware. Here is a simple example:
```ts
airgram.use(async (ctx, next) => {
  if('request' in ctx) {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(next())
      }, 3000)
    })
  }
  return next()
})
```

Also you can stop getting all updates throw the `TdJsonClient.prototype.pause()` method.

**Comment by jumoog** [comment]
thank you! `sendMessage` with 5 seconds helped!
