### ISSUE TITLE
[Airgram] tdweb instance has not initialized yet

### ISSUE THREAD

**Issue by likidu** [airgram/airgram#145]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I was trying to bump the Airgram from v3.1.1 to v4.0.0 recently. The previous test code basically I am using the same code for the webpack example to create an instance of Airgram and print out updates in console window. It worked fine with v3.1.1, but now with v4.0.0 I got this error.

```txt
Uncaught Error: [Airgram] tdweb instance has not initialized yet. Provider.ts:41
    at Provider.send (Provider.ts:41)
    at new AirgramCore (AirgramCore.js:122)
    at new Airgram (Airgram.ts:31)
    at instance$2 (App.svelte:23)
    at init (index.mjs:1470)
    at new App (App.svelte:46)
    at main.ts:3
    at main.ts:5
```

Here is the sample code that creates the Airgram instance and log into it: https://github.com/likidu/kaigram/blob/bump-tdlib-1.7.0/src/App.svelte

It looks like `@airgram/web` only updated `TdProvider` to `Provider`. I had not yet compared diff between v3.1.1 and v4 for `@airgram/core`. 

For `tdweb` as dependency, I tried both v1.6.10 and latest v1.7.0 which I compiled myself since I only need ASM.js support for my KaiOS app.

Any hints or comments could be helpful. Thanks.

**Comment by esindger** [comment]
Thank you for the report. Fixed.

**Comment by likidu** [comment]
Thanks for the quick reply! I can verify that it works now:

![image](https://user-images.githubusercontent.com/575981/103476495-47ae6280-4df1-11eb-8a80-3462ab3af692.png)
