### ISSUE TITLE
Pinned message in chat stops bot to respond

### ISSUE THREAD

**Issue by volodalexey** [airgram/airgram#15]
I have telegram room with me (as a user) and bot. Bot has administration rights and can view all messages.
I use Airgram for bot in this room.
If I - as a user pin some message - then bot freezes itself and refuses to work futher. I do not see any error messages, and I do not see any update events in console too. Only restart bot helps...

**Comment by volodalexey** [comment]
Also following might be related to this issue:
If I switch off Wi-Fi(internet) on my smartphone => add a couple of messages => switch Wi-Fi(internet) => messages are sending to my Telegram bot (which is always run on VPS server).
Result the same:
>  bot freezes itself and refuses to work futher. I do not see any error messages, and I do not see any update events in console too. Only restart bot helps..

**Comment by esindger** [comment]
I couldn't reproduce this issue. Bot keeps to receive updates when I pin or unpin messages. Can you create a repository with simple code which reproduce this behavior?

**Comment by volodalexey** [comment]
Checked this again - I can reproduce the issue.
https://github.com/volodalexey/airgram-user-and-bot-test - updated repo.
Just setup the project (see README).
Then `npm run build`
Then `npm run test` and within 20 seconds try to pin some message in your test group (I pin message as a user from my Android smartphone)

**Comment by volodalexey** [comment]
@esindger have you managed to reproduce this?
> Bot keeps to receive updates

Yes looks like bot receives `updates`, however `NewMessageUpdate` is never generated after I pin message.
I connected `airgram-debug` to se the difference in two cases:
1 => start bot => user send "/start" => bot receive `NewMessageUpdate` => bot reply
2 => start bot => userpin some message =>  user send "/start" => bot freeze
And I see that in 1 case I get `NewMessageUpdate`, in 2 no.
I found difference in output here (maybe this will help):
1:
```
...
airgram verbose 14:48:57.243 [UpdatesHandler] [3] handle() "updateNewMessage" ...
updates.use // my output in console
updates.on // my output in console
airgram info    14:48:57.249 [Client] callApi() "messages.sendMessage" ... // bot sends response
...
``` 
2:
```
...
airgram verbose 14:49:15.620 [UpdatesHandler] [3] handle() "updateNewMessage" ...
airgram verbose 14:49:15.621 [UpdatesHandler] [3] handleUpdateState() detected a pts hole (17292 > 17294 + 1), wait for true pts +1ms
airgram verbose 14:49:15.621 [Updates] [5] handled "updates" for 0.003sec +0ms
airgram verbose 14:49:16.120 [MtpClient][1] sendLongPoll() call checkLongPoll() +499ms
airgram verbose 14:49:16.121 [MtpClient][1] checkLongPoll() send longPoll +1ms
airgram debug   14:49:16.121 [MtpSerializer] writeInt() 2459514271  2459514271 http_wait[id]:int +1ms
airgram debug   14:49:16.122 [MtpSerializer] writeInt() 500  500 http_wait[max_delay]:int +0ms
airgram debug   14:49:16.122 [MtpSerializer] writeInt() 150  150 http_wait[wait_after]:int +0ms
airgram debug   14:49:16.123 [MtpSerializer] writeInt() 25000  25000 http_wait[max_wait]:int +1ms
...
```

**Comment by volodalexey** [comment]
I checked `0.1.14` and now bot works, however after "pin" => if user send some message => in bot I get this message without parent context (`ctx.parent is undefined`), and hense I can not detect some useful information.
Is there something I can do with this?

**Comment by airgram** [comment]
Please check `0.1.15` version.

**Comment by volodalexey** [comment]
Checked with version `0.1.15` - I still can not get parent context after.
Next message event after pin does not have parent context.

**Comment by volodalexey** [comment]
Sorry, problem is not in parent context. Will reply shortly.

**Comment by volodalexey** [comment]
Ok. It works. Awesome!
I had to take into account that after pin I will receive two messages:
```
{ _: 'updateNewMessage',
  message:
   { _: 'messageService',
     ...
     action: { _: 'messageActionPinMessage' } },
  pts: 18881,
  pts_count: 0 }

{ _: 'updateNewMessage',
  message: { _: 'message', ... },
  pts: 18886,
  pts_count: 1 }
```
