### ISSUE TITLE
Is there a way to save Authorization as JSON ?

### ISSUE THREAD

**Issue by itishermann** [airgram/airgram#151]
**Issue type:**

- [x] question
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

**Airgram version:**

- [x] `latest`
- [ ] `@next`
- [ ] `2.3.x` (or put your version here)

Hi all. So I'm working on a scholar project using airgram for node.js.
Every time I create a new `Auth`, it asks for the code sent to my account and I would like to know if there is a way to save the authorization data and share it from a project to another.
The main goal is to save the auth information and implement tests without having to type a new code.

This is the way i log an user in
```javascript
const config = {
  apiId: process.env.APP_ID,
  apiHash: process.env.APP_HASH,
  command: '/src/tdlib/libtdjson.so',
  logVerbosityLevel: 1
};

let auth = new Auth({
  code: () => prompt(`Please enter the secret code:\n`),
  phoneNumber: () => user.phone
});

const airgram = new Airgram(config);
airgram.use(auth);
```
Is there a way to save the user session and transfer it? 
If yes, how to do it?
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] question
    [ ] bug report

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by jumoog** [comment]
you can copy the SQLite Database (`db` Folder). But before copying the database, you must shut down the bot completely.

**Comment by itishermann** [comment]
> you can copy the SQLite Database (`db` Folder). But before copying the database, you must shut down the bot completely.

I've gone through the documentation and I saw that the method `provider.destroy()`.

```javascript
process.on('SIGINT', async () => {
    await airgram.provider.destroy();
    console.log('Closed airgram instance.');
});
```
This worked for me
