### ISSUE TITLE
Outdated constants package

### ISSUE THREAD

**Issue by MohamadKh75** [airgram/airgram#159]
**Issue type:**

- [ ] question
- [x] bug report
- [ ] feature request
- [ ] documentation issue

**Airgram version:**

- [x] `latest`
- [ ] `@next`
- [ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hey
I couldn't find the [`MessageSender.ts`](https://github.com/airgram/airgram/blob/master/packages/constants/src/union/MessageSender.ts) in the released package of `@airgram/constants`.
I guess the npm version is 3.0.0 and we miss the 3.1.0 which mentioned in the changelog 🤔

**Comment by MohamadKh75** [comment]
@esindger can we have an updated types?

**Comment by esindger** [comment]
Hello @MohamadKh75,
sorry for the late reply. I will update this package soon.

**Comment by esindger** [comment]
@MohamadKh75, I checked the `@airgram/constants` package. It was generated for TDLib 1.6.10, which is identical to version 1.7. Did you notice any mistakes?

**Comment by MohamadKh75** [comment]
Hello
Thanks for it!
I couldn't find the [`MessageSender.ts`](https://github.com/airgram/airgram/blob/master/packages/constants/src/union/MessageSender.ts) in the released package of `@airgram/constants`.
My mistake or yours 😁 ?

**Comment by esindger** [comment]
Please check it now, I fixed the `latest` tag on npmjs.com

**Comment by MohamadKh75** [comment]
Thanks!
Fixed 🥳
