### ISSUE TITLE
LOCK does not get removed after nodemon closes

### ISSUE THREAD

**Issue by amir3code** [airgram/airgram#16]
When I run the app and after a while I hit `ctrl + c` and app stops, It does not clean itself. It creates a file called `LOCK` in the `data` directory but it does not remove it on exit.  
Causing errors like this one:

```
  airgram error   16:02:00.395 [Client] [getMtpClient]: IO error: lock /home/meee/files/projects/mk/telegram_group_manager/data/airgram/LOCK: Resource temporarily unavailable {} +0ms
  airgram error   16:02:00.399 [Client] [startPolling]: IO error: lock /home/meee/files/projects/mk/telegram_group_manager/data/airgram/LOCK: Resource temporarily unavailable {} +2ms
```

**Comment by airgram** [comment]
I guess you use PouchDB as a storage? It's a persistent storage so the data hasn't been removed after process termination. By default, PouchDB uses file system (LevelDB) but you may use any other [adapter](https://pouchdb.com/adapters.html) or [pouchdb-server](https://github.com/pouchdb/pouchdb-server).

Some more information you can find in the [docs](https://github.com/airgram/airgram#data-store).

If you have more questions please feel free to ask.

**Comment by amir3code** [comment]
Yeah I have used pouchDB. Actually I have used your example as scaffolding for my projects (https://github.com/airgram/airgram-ts-example).  
I know its a persistent storage but persistent storages have a lock mechanism which pouchdb has. But it does not remove its own LOCK file from data directory. I think this problem is from pouchdb itself or maybe you forgot to call a `close` like function for the database.  
Anyway I am now using this in the first line of `index.ts` file:  

```
// remove the LOCK file before any work:
fs.unlink(__dirname + '/../data/airgram/LOCK', (err) => { })
```

**Comment by amir3code** [comment]
I found where the real problem was. If my code throws some error and crashes, pouchdb does not close and does not unlock the database before its own exit. Causing errors to occur, saying that database is locked (like the one I mentioned in the first comment).  
I dont know if this is a problem of pouchdb or your code but I have managed to get rid of it by removing the `LOCK` file before performing any action.

**Comment by airgram** [comment]
Airgram provides an abstract layer for creating data store and does not provide an implementation for any particular database, so we can't check if the 'LOCK' file exists. Please do it by yourself.

Please reopen the issue if you have some more questions.
