### ISSUE TITLE
run command as soon as connected

### ISSUE THREAD

**Issue by amir3code** [airgram/airgram#17]
I want to start a command but I want it to be started as soon as the connection is established to telegram servers.  
Where should I put this code into?  
Its like this:  

```
(async function () {
  airgram.client.messages.getDialogs({
    flags: 0,
    limit: 30,
    offset_date: 0,
    offset_id: 0,
    offset_peer: { _: 'inputPeerEmpty' },
  }).then((dialogs) => {
    if (dialogs._ == "messages.dialogs") {
      console.log(dialogs)
    }
    console.info(dialogs)
  }).catch((error) => {
    console.error(error)
  })
})();
```

**Comment by airgram** [comment]
You may use `Auth.prototype.getState` for checking authorization state:

```
const { auth, updates } = airgram
airgram.use(auth)
airgram.use(updates)

const getDialogs = () => airgram.client.messages.getDialogs({/* ... */})

auth.getState().then(({ userId }) => {
  if (userId) {
    return getDialogs()
  }
  return auth.login().then(getDialogs)
}).catch((error) => {
  console.error(error)
})
```

**Comment by amir3code** [comment]
Well I get what you say, but there is one problem and I have many problems with asynchronous codes :laughing: I dont know if it is only my problem but they seem very uncontrollable.  
Can you show me where to put this code in the `index.ts` file of your [airgram-ts-example](https://github.com/airgram/airgram-ts-example)?  

I have problem with that `auth.login` thing cause I have used it before in the `index.ts` file and I think it caused a **double login** and made the old stored keys to disappear and I should have removed the database and login again to make the system work again.  
Can I ommit the `auth.login` part? I mean can we assume that we are logged in by now and then get the state and check its value?

**Comment by esindger** [comment]
Okay, I will update the example today.

**Comment by amir3code** [comment]
Thanks for the response!  
I have another question, How this part of code in the [index.ts](https://github.com/airgram/airgram-ts-example/blob/master/src/index.ts) file know that we are connected to telegram servers and logged in. How does it tell? My question is about the whole asynchronous thing.

```typescript
// Get dialogs list
airgram.client.messages.getDialogs({
  flags: 0,
  limit: 30,
  offset_date: 0,
  offset_id: 0,
  offset_peer: { _: 'inputPeerEmpty' }
}).then((dialogs) => {
  console.info(dialogs)
}).catch((error) => {
  console.error(error)
})
```

**Comment by esindger** [comment]
> Can I ommit the auth.login part? I mean can we assume that we are logged in by now and then get the state and check its value?

If you use `Auth` middleware you don't should not to call `auth.login()` because middleware checks whether you are authorized or not (you won't be signed in twice). 

Method `auth.login()` unregister your previous access keys, so you need to check the current state like:
```
const { userId } = await auth.getState()
```
If `userId` is defined just skip the login step.

I think it's good idea to create `auth.onLogin(): Promise<ag.AuthDoc>` method:
```
auth.onLogin().then(({ userId }) => {
  // your own code
})
```

**Comment by amir3code** [comment]
Yeah yeah that would be perfect cause when I looked at the `index.ts` file I thought to myself that this is whole asynchronous and how can I guarantee that what I want gets executed when I am surely logged in. Thanks for your time!

**Comment by esindger** [comment]
> I have another question, How this part of code in the index.ts file know that we are connected to telegram servers and logged in. How does it tell? My question is about the whole asynchronous thing.

Method `airgram.client.messages.getDialogs()` knows nothing about authorization status. The `Auth` middleware checks authorization status and calls `auth.login()` if it is necessary.

**Comment by amir3code** [comment]
> Method airgram.client.messages.getDialogs() knows nothing about authorization status. The Auth middleware checks authorization status and calls auth.login() if it is necessary.

Aha so you mean If I am not logged in, It returns an error, right? So it assumes that we are logged in and it is not fault-tolerant.

**Comment by airgram** [comment]
Please wait for update. This behavior will be changed.

**Comment by airgram** [comment]
Now you can freely use `auth.login()`. Authorization keys wont be deleted. If user is already signed in, authorization will be skipped.

```
auth.login().then(async () => {
  // Start long polling
  await updates.startPolling()

  // Get dialogs list
  const dialogs = await airgram.client.messages.getDialogs({
    flags: 0,
    limit: 30,
    offset_date: 0,
    offset_id: 0,
    offset_peer: { _: 'inputPeerEmpty' }
  })

  console.log(dialogs)

}).catch((error) => {
  console.error(error)
})
```
Full example is [here](https://github.com/airgram/airgram-ts-example/blob/master/src/index.ts).
