### ISSUE TITLE
pls update airgram/web dependence tdweb package version to 1.7.2

### ISSUE THREAD

**Issue by Domingowen** [airgram/airgram#177]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Airgram version:**

[x ] `latest`
[] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
the airgram/web latest version dependencies tdweb package version still is 1.6.10. It makes me can't use addProxy API in airgram/web. Please update tdweb package version to 1.7.2. thank you.

**Comment by esindger** [comment]
Hello, Airgram has been updated.

```
npm install @airgram/web@tdlib-1.7.2
```
