### ISSUE TITLE
Comparison with TDLib?

### ISSUE THREAD

**Issue by laptou** [airgram/airgram#18]
I have three questions.

1. Does this library depend on/require TDLib?
2. Does this library have feature parity with TDLib yet?
3. If not, which features are currently incomplete?

**Comment by airgram** [comment]
TDLib and Airgram implement different API. Airgram is a wrapper for [Telegram API](https://core.telegram.org/#telegram-api) with support of all the features.

**Comment by laptou** [comment]
From looking at the code, it appears that this library implements the MTProto protocol directly. Is this the case?

**Comment by esindger** [comment]
You are right.

**Comment by laptou** [comment]
Okay, that mostly answers my question. Thank you ✨
