### ISSUE TITLE
TDLib version is not 1.7.0

### ISSUE THREAD

**Issue by MaruBlare** [airgram/airgram#184]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ ] `latest`
[ ] `@next`
[x] `4.0.1` 

**Steps to reproduce or a small repository showing the problem:**
Hello! We're using the 4.0.1 version of @airgram/web in our project. The TDLib version should be 1.7.0 as it's written in the documentation, but in fact, it's 1.6.10. 
![image](https://user-images.githubusercontent.com/29026396/144591749-bee3e56b-151c-4469-9570-fb27f0581e7d.png)

Could you please explain what is the problem? Maybe we should update something manually? Or something wrong with the dependencies in the @airgram/web?  
We have a problem with the authorization now, 'cause telegram requires to use at least 1.7.0 tdlib version (https://github.com/tdlib/td/issues/1758).

**Comment by jumoog** [comment]
yes you can use `@airgram/web@tdlib-1.7.2`

**Comment by sdcdsvsdv423** [comment]
The 1.6.10 version of `tdweb` has no difference from the version 1.7.0. In any case, now you can use version 1.8.
