### ISSUE TITLE
what about to update to tdlib 1.8.0?

### ISSUE THREAD

**Issue by davydof** [airgram/airgram#188]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

hi, subj, thanks :)

@jumoog @esindger

**Comment by jumoog** [comment]
sorry I'm not the right person..

**Comment by esindger** [comment]
Hello,
I will try to release tomorrow.

**Comment by sdcdsvsdv423** [comment]
New version is available.

**Comment by KishanBagaria** [comment]
@esindger Thank you for the quick update! I'm curious, how do you generate the TS defs – is there a script that can convert the .tl?

**Comment by jumoog** [comment]
Would be cool to have that
