### ISSUE TITLE
How to get list of admins within a group

### ISSUE THREAD

**Issue by amir3code** [airgram/airgram#20]
I have joined a group and I want to get list of all admins in the group. Thats a super group so it is a `channel`. How can I get that list?  
I have tested this code but it says `400 CHANNEL_INVALID` Which is not, cause I have joined it and I have copied the `channel_id` and `access_hash` from the `dialogs`.

```ts
airgram.client.channels.getParticipants({
  channel: {
    _: "inputChannel",
    channel_id: 1311111116,
    access_hash: 70232952222225240655,
  },
  filter: {
    _: "channelParticipantsAdmins",
  },
  limit: 10,
  offset: 0
})
  .then((valu) => {
    console.log(valu);
  })
  .catch((err) => {
    console.log(err);
    console.log(err.toString())
  })
```

**Comment by airgram** [comment]
Fixed in the last release. Parameter `access_hash` have to be a string.
