### ISSUE TITLE
How to send string as a callback data (using Airgram as a bot)?

### ISSUE THREAD

**Issue by volodalexey** [airgram/airgram#21]
I can send string as a callback data using Telegram bot API.
In [node-telegram-bot-api](https://github.com/yagop/node-telegram-bot-api/blob/b585957a0a492586fdf615a3bc186d78e6fd0338/examples/polling.js#L67):
```
reply_markup: {
      inline_keyboard: [
        [
          {
            text: 'Edit Text',
            callback_data: 'edit'
          }
        ]
      ]
    }
```
In [Telegraf](https://github.com/telegraf/telegraf/blob/f4db3863f1406d80d1cd94cac7b3572e3816d7d5/docs/examples/custom-router-bot.js#L10):
```
Telegraf.Extra.Markup.callbackButton('Add 10', 'add:10')
```
I want to send string as a callback data in Airgram too, however in typescript I see only `number[]`:
```
export interface KeyboardButtonCallback {
    _: 'keyboardButtonCallback';
    text: string;
    data: number[];
}
```
How can I send string as a data?

Second question.
I send inline keyboard with callback data:
```
messages.sendMessage({
    flags: 4,
    peer: { _: 'inputPeerChat', chat_id },
    message: text,
    random_id: String(randomId),
    reply_markup: {
      _: 'replyInlineMarkup',
      rows: [
        {
          _: 'keyboardButtonRow', buttons: [
            { _: 'keyboardButtonCallback', text: 'Callback', data: [ 123 ] }
          ]
        }
      ]
    }
  })
```
And I subscribe to receive this callback data:
```
  updates.on("updateBotCallbackQuery", (ctx: ag.UpdateContext, next) => {
    if (ctx.update._ === 'updateBotCallbackQuery') {
      console.log(ctx.update.data)
    }
  })
```
And in console I see that callback data is `Uint8Array [ 123 ]`. Why it is so?

**Comment by esindger** [comment]
According to `schema.tl` the `data` parameter have to be a byte's array:

```
keyboardButtonCallback#683a5e46 text:string data:bytes = KeyboardButton;
```
and
```
updateBotCallbackQuery#e73547e1 flags:# query_id:long user_id:int peer:Peer msg_id:int chat_instance:long data:flags.0?bytes game_short_name:flags.1?string = Update;
```

So if you want to use a string for the `data` parameter, you have to convert string to bytes and back. I create an [example](/airgram/airgram/blob/master/examples/custom-updates-context/index.ts) how extend updates context with `convertStringToBytes` and `convertBytesToString`.

**Comment by volodalexey** [comment]
Ok. Got it. I prefer to use these functions without context:
```
export function convertBytesToString(airgram: Airgram, bytes: number[]): string {
  const createDeserializer = airgram.container.get<ag.MtpDeserializerFactory>(TYPES.MtpDeserializerFactory);
  const data = createDeserializer(bytes)
  return data.fetchString()
}

export function convertStringToBytes(airgram: Airgram, str: string): number[] {
  const createSerializer = airgram.container.get<ag.MtpSerializerFactory>(TYPES.MtpSerializerFactory);
  const data = createSerializer();
  data.storeString(str)
  return arrayBufferToBytes(data.getBuffer())
}
```
It works! Thanks!

**Comment by volodalexey** [comment]
@esindger Can you help me in my question?

**Comment by esindger** [comment]
Method `answerInlineQuery` is not a part of `schema.tl`, this opportunity available only in the Bot API. Unfortunately, I couldn't find an analogue but in the docs of other mtproto client there is a [mention](https://docs.madelineproto.xyz/TD_docs/methods/answerInlineQuery.html) of the method. You may try to send request `Airgram.client.callApi<any, any>("answerInlineQuery", PARAMS)`. Probably it will work.

**Comment by airgram** [comment]
It wont work because `answerInlineQuery` is not in the schema and can not be serialized.

**Comment by volodalexey** [comment]
Got it, thanks!
It's a pity... I was thinking to completely replace `Telegram bot API` with `MTProto` and your awesome library!
