### ISSUE TITLE
channels.getMessages throws Error: Invalid vector object "Vector<int>"

### ISSUE THREAD

**Issue by AshwinTayson** [airgram/airgram#22]
Hello I'm just starting out with this library, I am using

```
const messages = await airgram.client.channels.getMessages({
    channel: {
      _: 'inputChannel',
      access_hash: '5890566463672636056',
      channel_id: 1224265728
    },
    limit: 10
  })

  console.log('Messages are here', messages)
```

This returns me

> [channels.getMessages]: Invalid vector object "Vector<int>" {}
> (node:18638) UnhandledPromiseRejectionWarning: Error: Invalid vector object "Vector<int>"
>     at MtpSerializer.storeObject (/home/ashwin/work/bl/airgram/node_modules/airgram/base/MtpSerializer.js:189:19)
>     at MtpSerializer.storeMethod (/home/ashwin/work/bl/airgram/node_modules/airgram/base/MtpSerializer.js:146:18)
>     at MtpClient.serializeRequest (/home/ashwin/work/bl/airgram/node_modules/airgram/base/MtpClient.js:218:37)
>     at /home/ashwin/work/bl/airgram/node_modules/airgram/base/MtpClient.js:131:28
>     at new Promise (<anonymous>)
>     at MtpClient.callApi (/home/ashwin/work/bl/airgram/node_modules/airgram/base/MtpClient.js:130:16)
>     at MtpRequest.execute (/home/ashwin/work/bl/airgram/node_modules/airgram/base/MtpRequest.js:111:31)
>     at /home/ashwin/work/bl/airgram/node_modules/airgram/base/MtpRequest.js:100:56
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:18638) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whichwas not handled with .catch(). (rejection id: 2)
> (node:18638) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

From other examples I see id should be included as an array. But what does this id represent? I tried giving the channel id in that it returns messageEmpty

**Comment by esindger** [comment]
Please check out parameters of the [chanels.getMessages](/docs/telegram-methods.md#channelsgetmessages) method. You should pass list of message id that you need to get.

**Comment by esindger** [comment]
I guess you need method [messages.getHistory](/docs/telegram-methods.md#messagesgethistory).

**Comment by AshwinTayson** [comment]
Sorry for the late message. Yes I needed to use the `messages.getHistory` It was not intuitive to name `channel.getMessages`. But I have another doubt. How can I download a image or any media? I dont want to open another issue/question for this.

I tried using
```
upload.getFile({
  location: {
    _: 'inputDocumentFileLocation',
    id: message.media.id,
    access_hash: message.media.access_hash
    version: ?
  }
})
```
But it throws **RpcError: CODE#400 LIMIT_INVALID**

I don't understand why getting one image needs limit and offset parameters. Also what number should be fed into version?

**Comment by esindger** [comment]
Try to add additional options:
```
client.upload.getFile({
      location: { ... },
      offset: 0,
      limit: 1024 * 1024
}, {
      isFileTransfer: true,
      createClient: true
})
```

> I don't understand why getting one image needs limit and offset parameters. 

This parameters described in `schema.tl`. Airgram does not change original Telegram API.

> Also what number should be fed into version?

Where did you take `location` value?

**Comment by AshwinTayson** [comment]
From the message.media property access_hash and id is available

**Comment by AshwinTayson** [comment]
Here is the actual message object

```
{
  _: 'message',
  pFlags: {
    post: true
  },
  flags: 17920,
  post: true,
  id: 11210,
  to_id: {
    _: 'peerChannel',
    channel_id: 1171605754
  },
  date: 1550556770,
  message: '',
  media: {
    _: 'messageMediaPhoto',
    pFlags: {},
    flags: 1,
    photo: {
      _: 'photo',
      pFlags: {},
      flags: 0,
      id: '6294134956242348146',
      access_hash: '11226369941418527484',
      date: 1550556770,
      sizes: [Array]
    }
  },
  views: 1643
}
```

**Comment by AshwinTayson** [comment]
Hello I've figured it. By the way this is a very useful library and I appreciate your effort. I didn't mean any disrespect or if I had been rude, I apologise. Its just a little frustrating with their API docs.

The answer is not to use id and access_hash instead use the sizes object in media.photo and get the desired size using the `secret,  volume_id and local_id`. I hope this issue is useful for someone who is in the same boat as me.
