### ISSUE TITLE
Airgram throws error while long polling

### ISSUE THREAD

**Issue by AshwinTayson** [airgram/airgram#23]
Can you tell me why Airgram throws the following errors?

> airgram error   15:16:24.504 [Client] [updateShort]: [38] handleUpdateChannelState() chat "1142964287" not found {} +0ms
>   airgram error   15:21:42.592 [Client] [updateShort]: [64] handleUpdateChannelState() chat "1083177497" not found {} +5m
>   airgram error   15:21:43.173 [Client] [updateShort]: [65] handleUpdateChannelState() chat "1083177497" not found {} +582ms
>   airgram error   15:26:08.761 [Client] [updates.channelDifferenceEmpty]: [85] handle() "updates.channelDifferenceEmpty" channel "undefined" not found {} +4m
>   airgram error   15:26:08.762 [Client] [updates.channelDifferenceEmpty]: [86] handle() "updates.channelDifferenceEmpty" channel "undefined" not found {} +2ms
>   airgram error   15:26:08.764 [Client] [updates.channelDifferenceEmpty]: [87] handle() "updates.channelDifferenceEmpty" channel "undefined" not found {} +1ms
>   airgram error   15:26:08.765 [Client] [updates.channelDifferenceEmpty]: [88] handle() "updates.channelDifferenceEmpty" channel "undefined" not found {} +1ms
>   airgram error   15:26:08.766 [Client] [updates.channelDifferenceEmpty]: [89] handle() "updates.channelDifferenceEmpty" channel "undefined" not found {} +1ms
>   airgram error   15:26:08.767 [Client] [updates.channelDifferenceTooLong]: [90] handle() "updates.channelDifferenceTooLong" channel "undefined" not found {} +1ms
>   airgram error   15:29:22.937 [UpdatesHandler] [98] handle() "updates.channelDifference" channel_id is undefined +3m
>   airgram error   15:31:17.437 [UpdatesHandler] [108] handle() "updates.channelDifference" channel_id is undefined +2m

The first 3 errors is related to the admin deleting the message from the channel I guess. I'm not sure about the others and why these are thrown.

**Comment by airgram** [comment]
```
airgram error 15:16:24.504 [Client] [updateShort]: [38] handleUpdateChannelState() chat "1142964287" not found {} +0ms
```

This error means that the chat does not found in the local storage and so can not be updated.
It can be happen if you delete the message from a channel just after start of telegram client (before getting difference). In the most cases you may ignore this error. If you need to load the chat state, call `airgram.updates.getDifference()`.

```
airgram error 15:26:08.761 [Client] [updates.channelDifferenceEmpty]: [85] handle() "updates.channelDifferenceEmpty" channel "undefined" not found {} +4m
```

I don't know why channel is `undefined`. It depends on your previous operations. Could you attach here the debug log? Do not forget to remove sensitive data.

**Comment by AshwinTayson** [comment]
Is there a way to turn off Logger. I'm not worried about channel deleting messages. When I'm in development I can turn on debug mode

**Comment by airgram** [comment]
You may implement and inject your own logger:
```
import { ag, Airgram, TYPES } from 'airgram'
import BaseLogger from 'airgram/base/Logger'

@injectable()
class DevNullLogger extends BaseLogger {
  protected log (level, message) {
    // do nothing
  }
}

const airgram = new Airgram(/* config */)

airgram.bind<ag.Logger>(TYPES.Logger).to(DevNullLogger)
```

**Comment by AshwinTayson** [comment]
My project is Javascript based. Can you tell me how I can use injectable for JS?

I tried this

```
const BaseLogger = require('airgram/base/Logger')

class DevNullLogger extends BaseLogger {
  log (level, message) {
    // do nothing
  }
}

const airgram = new Airgram({id: process.env.APP_ID, hash: process.env.APP_HASH})
airgram.bind(TYPES.Logger).to(DevNullLogger)
```

And It throws **Class extends value #<Object> is not a constructor or null** for _extends BaseLogger_

**Comment by airgram** [comment]
Please try the following code to inject a class in JavaScript:

```
const inversify = require('inversify')

inversify.decorate(inversify.injectable(), DevNullLogger)
```
