### ISSUE TITLE
Feature Request: Please provide support for socks/socks5 proxy

### ISSUE THREAD

**Issue by amir3code** [airgram/airgram#25]
Hello and thanks for the great work.  
As you know telegram is blocked in many countries do to political problems with the governments, countries like Iran, Russia, etc.  
At this moment VPNs are all blocked in my country and I was using tor and `torify` to run airgram
```shell
torify yarn start
```
and I see that it hits some problems and it can not work through tor.  
I wanted you to provide support for socks5 proxy (as the telegraf project does it) to help us bypass these limitations. Thanks in advanced.

**Comment by airgram** [comment]
Since version `0.1.20` you can provide your own `axios` instance with custom options:
```
import axios from 'axios'
import * as https from 'https'
import { ag, Airgram, TYPES } from 'airgram'
import MtpNetwork from 'airgram/base/MtpNetwork'

const airgram = new Airgram({ /* options */ })

airgram.bind<MtpNetwork>(TYPES.MtpNetwork).to(MtpNetwork).onActivation((context, network) => {
  const httpsAgent = new https.Agent()
  network.axios = axios.create({ httpsAgent })
  return network
})
```
You can try this [recipe](https://medium.com/@paynoattn/using-a-socks-proxy-to-make-requests-in-node-js-ba5125c7999f) to create socks5 https agent.

**Comment by amir3code** [comment]
Actually I did all of that but it did not work. I'll try to stick to using torify (it mostly works) and VPN for now until `airgram` gets a built-in support for socks proxy.  
Thanks.

**Comment by airgram** [comment]
Check whether it works with the `0.1.21` version or not. If not, please provide some more information about errors.

**Comment by qwertvasilii** [comment]
@airgram it throws error
Error: Missing required @injectable annotation in: Anonymous function: [object Object].

**Comment by k0t0fey** [comment]
I also confirm this feature does not work. 
My code:
```
    const airgram = new Airgram({id: conf.api_id, hash: conf.api_hash});

    // Proxy
    airgram.bind(TYPES.MtpNetwork).to(MtpNetwork).onActivation((context, network) => {
        network.axios = axios.create({
            httpsAgent: new https.Agent(),
        });
        return network;
    });
```
After default timeout throw error:
```
Error: Request timeout exceeded.
    at Timeout._onTimeout (tg\node_modules\airgram\base\Client.js:280:89)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by airgram** [comment]
@qwertvasilii, can you share your code?

@k0t0fey, I've just checked your code. It works for me. If you are in Russia or in some other banned area, try to use proxy as described [here](https://medium.com/@paynoattn/using-a-socks-proxy-to-make-requests-in-node-js-ba5125c7999f).

**Comment by k0t0fey** [comment]
Yep, I'am from Russia, but I use vpn on my router, so all banned services working for me.
For example, if I disable part with `network.axios` and request any tg-method, then it work fine:
```
const dialogs = await airgram.client.messages.getDialogs({
                // flags: 0,
                limit: 100,
                offset_date: last_date,
                offset_id: 0,
                offset_peer: { _: 'inputPeerEmpty' }
            });
```
dialogs contains all actual data:
![screen](https://i110.fastpic.ru/big/2019/0514/72/7be8954e341687e3f2bf3ae3b9768772.png)

**Comment by airgram** [comment]
@k0t0fey, can you upload `verbose` log with and without network settings?

**Comment by k0t0fey** [comment]
[verbose_log_without_network_stg.log](https://yadi.sk/d/sWNJN1CQ59BTGw)
[verbose_log_with_network_stg.log](https://yadi.sk/d/yoGGeLWPk7U2xg)

the same error as described by @qwertvasilii
`  airgram error   15:58:17.254 [MtpClient][1] sendScheduledRequest() "Missing required @injectable annotation in: Anonymous function: [object Object]." +3ms
`

**Comment by k0t0fey** [comment]
Any ideas how to solve this problem?

**Comment by airgram** [comment]
I can't reproduce this error. Please can you clone [this repo](https://github.com/airgram/airgram-ts-example/tree/test-network) (`test-network` branch) and check whether the example works for you or not.

**Comment by k0t0fey** [comment]
Very likely the problem occurs with a projects based in a pure js.

**Comment by airgram** [comment]
Try to import `MtpNetwork` this way:
```
const MtpNetwork = require('airgram/base/MtpNetwork').default
```

**Comment by k0t0fey** [comment]
Thx, now all works! =)
