### ISSUE TITLE
Feature Request: Telegram Bot API mode

### ISSUE THREAD

**Issue by volodalexey** [airgram/airgram#26]
I have a lot of difficulties to use [telegraf](https://github.com/telegraf/telegraf) or [node-telegram-bot-api](https://github.com/yagop/node-telegram-bot-api). Looks like these libraries are abandoned. Even my pull [request to telegraf](https://github.com/telegraf/telegraf/pull/601) is hanging more than two month. These libraries are also not "True TypeScript" - they have just type declarations that [is always outdated](https://github.com/telegraf/telegraf/issues?utf8=%E2%9C%93&q=is%3Aopen+typescript)...
I see that "native" Telegram Bot API [has more advantages](https://github.com/airgram/airgram/issues/21) for bots than "hardcore" MtProto (another example of limitaion in [telethon](https://github.com/LonamiWebs/Telethon/issues/36) ). Using "Telegram Bot API" you don't need storage implementation, encryption, etc...

Is it possible to make Aigram to have two use-cases:
1) Airgram as MtProto (for user or for bot with a lot of limitations):
```
const airgram = new Airgram({
  mode: 'MtProto',
  id: ..., 
  hash: ...,
  token: ...,
})
```

2) Airgram as Telegram Bot API (for bot only):
```
const airgram = new Airgram({
  mode: 'BotAPI',
  token: ...,
})
// in this case probably better to use something different like?
airgram.bot.sendMessage(...)
airgram.bot.on('text', ...)
```

How hard is it to implement in current architecture? Is it possible? Do you have such interest?

I feel that Airgram can be extremly popular because of this feature, because a lot of coders just need bot features.
As a disadvantage this might lead to a lot of support-features that Bot API has but MtProto does not.

**Comment by airgram** [comment]
The last few days I thought about the possibility of creating a single client for Bot API and MTProto. I don't see a clear way to do it because implementation of the api, network and other layers are very different. 

It’s better to create separate library. I can implement strong typed wrapper for bot api the same way as for this library but I need help with other components like network layer and etc. If you are ready to become a member of the project and help with development and supporting of the library, we can do it.

**Comment by volodalexey** [comment]
I can spend some time at weekends for now. Unfortunately I do not have much time for this.
My thought was to re-use as much as possible from Airgram.
If you create separate library - at some point we will have divergent Types.
As a summary - I think I do not have enough time for a separate library.
Anyway thanks for your effort!

**Comment by airgram** [comment]
Please check out [TDLib implementation](https://github.com/airgram/airgram). New version have to solve your difficulties, because it includes both API (bot and client).
