### ISSUE TITLE
Need Support for multi login in one program

### ISSUE THREAD

**Issue by ktjd123** [airgram/airgram#32]
## 🚀 Feature Request

[1.0.1 ] TDLib version
[ ] MTProto version

It would be nice if airgarm can handle multi login.

What i See is airgram can only store 1 auth information. it would be much nicer if it can handle multi login

**Comment by airgram** [comment]
Airgram supports multi login. Provide different directories for each authorization by option `databaseDirectory`:

```
// Authorization 1
const airgram1 = new Airgram({
  databaseDirectory: './data/user-1',
})

// Authorization 2
const airgram2 = new Airgram({
  databaseDirectory: './data/user-2',
})
```

**Comment by ktjd123** [comment]
Thank you. Very nice work :)
