### ISSUE TITLE
Example for getting chats list of "me".

### ISSUE THREAD

**Issue by ktjd123** [airgram/airgram#33]
## 🚀 Feature Request

[ 1.0.1] TDLib version
[ ] MTProto version

It would be nice if there is example of getting chat list of "me" in getting started section since I'm not able to find api method for it 😂 and it would be same for others

**Comment by ktjd123** [comment]
Maybe need info about equivalent function of messages.getDialogs

**Comment by airgram** [comment]
Use the [`getChats`](https://github.com/airgram/airgram-api/blob/master/docs/td-methods.md#apigetchats) API method instead of `messages.getDialogs`:

```
airgram.api.getChats({
    limit: 100,
    offsetChatId: 0,
    offsetOrder: '9223372036854775807' // 2^63
  }).then((chats) => {
    console.log(chats)
  })
```

 You will receive chat users by the `updateUser` update:

```
import { User } from 'airgram-api'

const userMap = new Map<number, User>()

airgram.updates.on('updateUser', ({ update }, next) => {
  userMap.set(update.user.id, update.user)
  return next()
})
```

**Comment by airgram** [comment]
@ktjd123, when you create an issue, please remove all unnecessary text of the issue template, when you create an issue.

**Comment by ktjd123** [comment]
When I give number for offsetOrder with pure JS It throws Error. maybe this needs to be fixed

**Comment by airgram** [comment]
What a number you pass to `offsetOrder`?

**Comment by ktjd123** [comment]
passed number is 9223372036854775807

the code is 

```js

const chats = await airgram.api.getChats({
    limit: 100,
    offsetChatId: 0,
    offsetOrder: 9223372036854775807,
  });

  console.log(chats);

```

and the ERROR Message is 

```
[ 1][t 0][1560668954.425536156][ClientJson.cpp:76][&status.is_error()]  Failed to parse [request:{\0042limit\0042:100,\0042offset_chat_id\0042:0,\0042offset_order\0042:9223372036854776000,\0042@extra\0042:\00423978a17c-57a3-4fd2-9325-77fd53814eee\0042,\0042@type\0042:\0042getChats\0042}] [Error : 0 : Can't parse "9223372036854776000" as number]
```

**Comment by airgram** [comment]
Just pass `offsetOrder` parameter as a string:
```
const chats = await airgram.api.getChats({
    offsetOrder: '9223372036854775807'
  });
```

**Comment by tongjinle** [comment]
> Just pass `offsetOrder` parameter as a string:
> 
> ```
> const chats = await airgram.api.getChats({
>     offsetOrder: '9223372036854775807'
>   });
> ```

but sometime i dont get **ALL** chats in return,can you tell me why and how to get all chats
