### ISSUE TITLE
api getme fetching very slowly after 4 times

### ISSUE THREAD

**Issue by ktjd123** [airgram/airgram#38]
## 🐛  Bug Report

**Current Behavior**
get me api is fetching very slowly after 4 times of fetch after program starts

**Input Code**
- REPL or Repo link if applicable:

```js
 for (let i = 0; i < users.length; i += 1) {
    const user = users[i];

    const airgram = new Airgram({
      apiId: 476408,
      apiHash: 'da45ac9f71cb62bccb756e7f0b1a10b9',
      logVerbosityLevel: 1,
      databaseDirectory: `./db/${user.phoneNumber}`,
    });
    const auth = new Auth(airgram);

    await auth.use({
      code: '000000',
      phoneNumber: user.phoneNumber,
    });

    await airgram.api
      .getMe()
      .then(async (res) => {
        console.log('logged in true: ', res.firstName, res.lastName);
        user.alive = true;
        user.lastUsed = new Date();
        await user.save();
      })
      .catch(async () => {
        console.log('logged in false : ', user.phoneNumber);
        user.alive = false;
        await user.save();
      });

    console.log(i);
  }
```

result is 

```js
logged in true:  성민 김
0
logged in true:  Phone For dev
1
logged in true:  김 뭐시갱이
2
logged in true:  그냥 사람
3
```

and then takes like minuts 

**Expected behavior/code**
fetch fast. I'm not sure if this is happening to other apis.

**Environment**
- Airgram version: 1.0.3
- Node/npm version: v10, 6.9.0
- Language: JS

**Possible Solution**
Maybe bottleneck is happening somewhere

**Comment by airgram** [comment]
It's probably related to [this issue](https://github.com/Bannerets/tdl/issues/18#issuecomment-443472139).

**Comment by ktjd123** [comment]
Adding client.pause() will solve it

**Comment by ktjd123** [comment]
@airgram client.pause is removed in new version?

**Comment by airgram** [comment]
It has moved to `provider` property:

```ts
airgram.provider.pause()
```

**Comment by ktjd123** [comment]
works perfect
