### ISSUE TITLE
Register new number

### ISSUE THREAD

**Issue by ktjd123** [airgram/airgram#39]
## 🚀 Feature Request

[ 1.0.3] TDLib version
[1.4 ] MTProto version

**Is your feature request related to a problem? Please describe.**
Register new number

**Describe the solution you'd like**
add method

**Comment by airgram** [comment]
If I understood your question correct, you want to register new phone number by Airgram? 

Registration is implemented by the same [API method](https://github.com/airgram/airgram-api/blob/master/docs/td-methods.md#apicheckauthenticationcode) as authentication. So you can do it now, but you have to provide `firstName` and `lastName`:

```
import { Airgram, Auth } from 'airgram'

const airgram = new Airgram()
const auth = new Auth(airgram)

auth.use({
  // ...
  firstName: 'John',
  lastName: 'Smith'
})
```

P.S.: Telegram may decline registration from your application and return an error `PHONE_NUMBER_APP_SIGNUP_FORBIDDEN`. This error is not related to Airgram.

**Comment by ktjd123** [comment]
Cool, this is what I was curious about. is there method to get code by call??

like official telegram app calls after 2 mins.

**Comment by airgram** [comment]
Please check out the [`resendAuthenticationCode`](https://github.com/airgram/airgram-api/blob/master/docs/td-methods.md#apiresendauthenticationcode) API method.

**Comment by ktjd123** [comment]
Can I ask if how I can mix Auth and api method together 😭

I tried the code

```js
  await auth.use({
    code: async () => {
      await airgram.api.resendAuthenticationCode();
      prompt('Please enter code');
    },
    phoneNumber,
    firstName: 'some',
    lastName: 'name',
  });

```

and I think it's not how it works.

I always appreciate your work

**Comment by airgram** [comment]
If you want to catch updates of the authorization state, you should add your middleware above `Auth` initialization:

```typescript
import { Airgram, Auth } from 'airgram'
import { AUTHORIZATION_STATE, UPDATE } from 'airgram-api'

const airgram = new Airgram({
  // ...
})

let timer
airgram.on(UPDATE.updateAuthorizationState, ({ update }, next) => {
  const { authorizationState } = update
  if (authorizationState === AUTHORIZATION_STATE.authorizationStateWaitCode) {
    timer = setTimeout(() => airgram.api.resendAuthenticationCode(), 120 * 1000)
  } else {
    clearTimeout(timer)
  }
  return next()
})

const auth = new Auth(airgram)
auth.use({ /* ... */ })
```

This example will work since the next release. At the time, method `resendAuthenticationCode` is blocked by `Auth` middleware.

**Comment by ktjd123** [comment]
Thank you ! 

Can I know when will the next release will be released ??

@airgram

**Comment by airgram** [comment]
I guess it will be tomorrow or the day after tomorrow.

**Comment by ktjd123** [comment]
Thank you :)

**Comment by ktjd123** [comment]
> If you want to catch updates of the authorization state, you should add your middleware above `Auth` initialization:
> 
> ```ts
> import { Airgram, Auth } from 'airgram'
> import { AUTHORIZATION_STATE, UPDATE } from 'airgram-api'
> 
> const airgram = new Airgram({
>   // ...
> })
> 
> let timer
> airgram.on(UPDATE.updateAuthorizationState, ({ update }, next) => {
>   const { authorizationState } = update
>   if (authorizationState === AUTHORIZATION_STATE.authorizationStateWaitCode) {
>     timer = setTimeout(() => airgram.api.resendAuthenticationCode(), 120 * 1000)
>   } else {
>     clearTimeout(timer)
>   }
>   return next()
> })
> 
> const auth = new Auth(airgram)
> auth.use({ /* ... */ })
> ```
> 
> This example will work since the next release. At the time, method `resendAuthenticationCode` is blocked by `Auth` middleware.

Should use  if (authorizationState._ === AUTHORIZATION_STATE.authorizationStateWaitCode) instead of  if (authorizationState === AUTHORIZATION_STATE.authorizationStateWaitCode)
