### ISSUE TITLE
JsonProvider undefined

### ISSUE THREAD

**Issue by thedevxen** [airgram/airgram#40]
## 🐛  Bug Report

**Current Behavior**
JsonProvider returns undefined.

**Input Code**

```js
const airgram = require('airgram');
const { JsonProvider } = airgram;
```

**Expected behavior/code**
In the docs it's given JsonProvider has been used, but when I try to use the same code it returns undefined

**Environment**
- Airgram version: 1.0.3
- Node/npm version: v10.15.3 / 6.4.1
- Language: JavaScript

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by airgram** [comment]
Hello, you see documentation for next release `1.1.0`. You can install it like this:

```
# npm i airgram@next
```
Note: `WebProvider` is not ready yet.

Documentation for the `1.0.3` version is [here](https://github.com/airgram/airgram/blob/c13f9c8334edf41b6c643131fa613b807a868f23/README.md).

Sorry for the temporary inconvenience.
