### ISSUE TITLE
is 1.1.0-0 new and useable version??

### ISSUE THREAD

**Issue by ktjd123** [airgram/airgram#41]

**Comment by airgram** [comment]
At the moment, you can use `1.1.0-0` in node environment. There are some issues related to browser version. 

```
npm i airgram@next
```

**Comment by ktjd123** [comment]
Cool Thx

**Comment by thedevxen** [comment]
i've an issue, i am trying to send a message to a specific user but it says "Chat not found" although the chat id is perfectly correct

![image](https://user-images.githubusercontent.com/31907722/60262516-f1a75780-98fb-11e9-92f1-9179e16d0f58.png)
