### ISSUE TITLE
tdweb peer dependency typescript error

### ISSUE THREAD

**Issue by ktjd123** [airgram/airgram#43]
## 🐛  Bug Report

**Current Behavior**
typescript error for tdweb could not found declaration for tdweb

**Input Code**
- REPL or Repo link if applicable:

```js
node_modules/airgram/dist/components/TdWebProvider.d.ts(1,42): error TS7016: Could not find a declaration file for module 'tdweb'. '/Users/peter/Program/airgram-ts/node_modules/tdweb/dist/tdweb.js' implicitly has an 'any' type.
  Try `npm install @types/tdweb` if it exists or add a new declaration (.d.ts) file containing `declare module 'tdweb';
```

**Expected behavior/code**
tdweb should not be imported yet

**Environment**
- Airgram version: 1.1.0-0
- Node/npm version: node v10
- Language: Typescript

**Possible Solution**
wait until @types/tdweb is ready then support tdweb.

**Comment by esindger** [comment]
Temporary you can copy this file into your project: https://github.com/airgram/airgram/blob/master/src/types/tdweb.d.ts

**Comment by ktjd123** [comment]
Works perfectly
