### ISSUE TITLE
unexpected end of json on entering chat

### ISSUE THREAD

**Issue by ktjd123** [airgram/airgram#45]
**Issue type:**

[ ] question
[v] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ ] `latest`
[ ] `@next`
[v] `1.1.1

**Steps to reproduce or a small repository showing the problem:**

join chat using api

```ts
await airgram.api
        .joinChatByInviteLink({ inviteLink })
        .then(() => {
          console.log("user", user.phoneNumber, "joined chat");
        })
        .catch((err) => {
            console.error(err)
        });
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] question
    [ ] bug report

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by airgram** [comment]
Can you show some TDLib response, which one is not correct JSON and could not be parsed?
