### ISSUE TITLE
Breaking old code

### ISSUE THREAD

**Issue by kolay-v** [airgram/airgram#47]
**Issue type:**

[ ] bug report

**Airgram version:**

[ ] `@next`

**Steps to reproduce or a small repository showing the problem:**
github.com/kolay-v/spotify2tg

@next breaking old code.
```
/home/kolay/spotify2tg/node_modules/airgram/dist/Airgram.js:79
            throw new Error('The `provider` option is required.' +
            ^

Error: The `provider` option is required.See: https://github.com/airgram/airgram/blob/master/README.md#providers
    at new Airgram (/home/kolay/spotify2tg/node_modules/airgram/dist/Airgram.js:79:19)
    at Object.<anonymous> (/home/kolay/spotify2tg/main.js:20:17)```

**Comment by kolay-v** [comment]
also i have question. how i can provide prefer_ipv6 option to tdlib

**Comment by esindger** [comment]
At the moment, the last version is `v1.1.2` (do not use `@next` one).

> also i have question. how i can provide prefer_ipv6 option to tdlib

Please check out [`setOption`](https://github.com/airgram/airgram-api/blob/master/docs/td-methods.md#apisetoption) API method.

```ts
await airgram.api.setOption({
  name: 'prefer_ipv6',
  value: {
    _: 'optionValueBoolean',
    value: true
  }
})
```

**Comment by kolay-v** [comment]
Thank you
