### ISSUE TITLE
Is Python required to install Airgram?

### ISSUE THREAD

**Issue by youk** [airgram/airgram#49]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**

Python is not listed in the [requirements](https://github.com/airgram/airgram#requirements). When installing, however, I get the error due to missing Python installation. Is there any way around this or is Python required to install Airgram?

```
$ yarn add airgram
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠐ ref-napi
error ***\node_modules\ref-napi: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: ***\node_modules\ref-napi
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.15.3 | win32 | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON

*** skipped for brevity ***

gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "***\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ***\node_modules\ref-napi
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

**Comment by esindger** [comment]
Thank you for the report.
Actually, Airgram uses [`ffi-napi`](https://github.com/node-ffi-napi/node-ffi-napi#installation), which requires [`node-gyp`](https://github.com/nodejs/node-gyp#installation) library. The last one needs Python.

Here is an [instruction](https://github.com/nodejs/node-gyp#on-windows) how to install `node-gyp` on Windows.

Documentaton will be fixed.
