### ISSUE TITLE
How to properly call getChatHistory?

### ISSUE THREAD

**Issue by Gamaranto** [airgram/airgram#53]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x ] `latest`
[ ] `@next`
[ ] `1.1.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

### Program 1 

```javascript require("dotenv").config();
const { Airgram, Auth, prompt } = require("airgram");

const airgram = new Airgram({
  apiId: process.env.APP_ID,
  apiHash: process.env.APP_HASH,
  command: path.join(__dirname, "..", process.env.TDLIB_COMMAND),
  logVerbosityLevel: 2
});

airgram.use(
  new Auth({
    code: () => prompt(`Please enter the secret code:\n`),
    phoneNumber: () => prompt(`Please enter your phone number:\n`),
    password: () => prompt(`Please enter your password:\n`)
  })
);

(async function() {
let ch = await airgram.api.getChatHistory({
    chatId: -1001210046212,
    limit: 10,
    onlyLocal: false
  });
console.log({ ch });
})();
```

 Will log   
```javascript 
{
  _: 'getChatHistory',
  airgram: [Getter],
  state: [Getter],
  request: [Getter],
  response: { _: 'error', code: 6, message: 'Chat not found' }
}
```

### Program 2

```javascript
require("dotenv").config();
const { Airgram, Auth, prompt } = require("airgram");

const airgram = new Airgram({
  apiId: process.env.APP_ID,
  apiHash: process.env.APP_HASH,
  command: path.join(__dirname, "..", process.env.TDLIB_COMMAND),
  logVerbosityLevel: 2
});

airgram.use(
  new Auth({
    code: () => prompt(`Please enter the secret code:\n`),
    phoneNumber: () => prompt(`Please enter your phone number:\n`),
    password: () => prompt(`Please enter your password:\n`)
  })
);

(async function() {
  await airgram.api.getChats({
    limit: 100,
    offsetOrder: "9223372036854775807"
  });

let ch = await airgram.api.getChatHistory({
    chatId: -1001210046212,
    limit: 10,
    onlyLocal: false
  });
console.log({ ch });
})();

```

Will log : 
```javascript
{
  _: 'getChatHistory',
  airgram: [Getter],
  state: [Getter],
  request: [Getter],
  response: { _: 'messages', totalCount: 1, messages: [ [Object] ] }
}
```
Why do I need to call `getChats`before `getChatHistory `?  What am I doing wrong?

Also, how do I fetch more than 1 message?

**Comment by esindger** [comment]
Hello,
it's [expected behaviour](https://github.com/tdlib/td/issues/740#issuecomment-544127844).

**Comment by Gamaranto** [comment]
Thank you for that.

For anyone wondering the way to go is to fetch the last message id with a call to `getChatHistory` and then use that as the `fromMessageId` parameter in a subsequent call to `getChatHistory`

I didn't find this documented anywhere but it looks like the message ids are generated by incrementing the last message id by `1.048.576`, so you can do the math and start from an earlier message.

**Comment by levlam** [comment]
@Gamaranto Don't do the math on message identifiers, or you will definitely miss some messages. Just pass identifier of the last received message in the previous request as `fromMessageId` to the next request as described in https://core.telegram.org/tdlib/getting-started#getting-chat-messages.
