### ISSUE TITLE
How to use Proxies with Airgram?

### ISSUE THREAD

**Issue by Gamaranto** [airgram/airgram#55]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ x] `latest`
[ ] `@next`
[ ] `1.1.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm writing a script to download my own messages, but I'm getting rate limited, in particular, I get this error : 
```
[ 2][t 4][1571754165.439467192][NetQueryDelayer.cpp:81][#1][!NetQueryDelayer]   Delay: [Query:[id:4915200][tl:0xdcbb8260][state:Query]] [timeout:30.000000][total_timeout:30.000000] because of [Error : 420 : FLOOD_WAIT_30]
```

Why am I getting this error? 

If I can fix it by using proxies, how can I do that with Airgram?

**Comment by esindger** [comment]
This error is not related to Airgram, it comes from TDLib.

For connection with proy use [addProxy](https://airgram.io/api-reference/api-methods/addProxy) method. 

P.S.: web version does [not support](https://github.com/tdlib/td/issues/729) proxies.
