### ISSUE TITLE
how to use username instead of userId for user info lookup

### ISSUE THREAD

**Issue by wintersonic** [airgram/airgram#56]
**Issue type:**

[x] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `1.1.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I want to execute `api.getUserFullInfo()` with a username. It seems like the official API allows this kind of search and also other libraries like the python3 library Telethon allow to pass a username instead of an ID. How is this possible with Airgram? Right now I am running `api.searchPublicChat()` first and use the ID then to execute the other function. This is a little redundant.

**Comment by esindger** [comment]
Airgram implements [straightforward TDLib API](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L2933-L2934), there is not special method to get full information about a user by his username. 

```
//@description Returns full information about a user by their identifier @user_id User identifier
getUserFullInfo user_id:int32 = UserFullInfo;
```

You need to save updates and take user id from the store.

```typescript
// Store.ts

import { UserUnion } from 'airgram'

export class Store {
  public readonly users: Map<number, UserUnion> = new Map()
  public readonly userIds: Map<string, number> = new Map()

  setUser (user: UserUnion) {
    this.users.set(user.id, user)
    this.userIds.set(user.username, user.id)
  }
}
```

```typescript
// index.ts

import { Airgram, toObject } from 'airgram'
import { Store } from './Store'

const store = new Store()

const airgram = new Airgram({
  // ...
  context: { $store: store }
})

airgram.on('updateUser', async ({ $store, update }, next) => {
  const { user } = update
  $store.setUser(user)
  return next()
});
```

Then you can easily get user id by username:

```typescript
const userId = store.userIds.get('john_doe')

// or inside middleware:
const userId = ctx.$store.userIds.get('john_doe')
```
