### ISSUE TITLE
[Browser] How to access File after download?

### ISSUE THREAD

**Issue by viet0511** [airgram/airgram#59]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x ] `latest`
[ ] `@next`
[ ] `1.1.x` (or put your version here)

In browser, I downloaded a file with downloadFile method. How can I access that file after download is done (isDownloadingCompleted=true) ?
![image](https://user-images.githubusercontent.com/1768904/67918473-145dbb80-fbcf-11e9-884f-9fe1c8d9b2cf.png)

**Comment by viet0511** [comment]
Thank, I saw that function but trying find another way to direct access TDlib file system for better perfomance like docs said. (look at telegram-react I don't see they use readFilePart function)

**Comment by ne0c0de** [comment]
> You can get file data in Blob format by the [api.readFilePart()](https://airgram.io/api-reference/api-methods/readFilePart) method:
> 
> ```ts
> const { response } = await airgram.api.readFilePart({
>   fileId: 1
> })
> const file = response.data // Blob
> ```

Hello @esindger I tried to use readFilePart but it's returning empty data to me even if I give count parameter as 0 (which means it should return all data of image)

Is there a bug or something?
