### ISSUE TITLE
[Browser] Is Airgram ready to run on multiple tab in same browser?

### ISSUE THREAD

**Issue by viet0511** [airgram/airgram#60]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x ] `latest`
[ ] `@next`
[ ] `1.1.x` (or put your version here)

Can Airgram run on multiple tab in same browser?
I was try but both tab close the connection.
![image](https://user-images.githubusercontent.com/1768904/67933561-9f9f7700-fbf8-11e9-9427-61ac3637afda.png)

**Comment by esindger** [comment]
It's not related to Airgram, `tdweb` supports only one active tab.

**Comment by viet0511** [comment]
I can see https://web.telegram.org/ can use more than one tab at a time (Earlier 1-2 years ago it can't).
I found they use http long pooling instead of ws like airgram. Are they not using tdweb?

**Comment by esindger** [comment]
No, they have implemented their own mtproto client version.
