### ISSUE TITLE
[Web]: Use the exact version of the Tdlib/Tdweb

### ISSUE THREAD

**Issue by sh-a-v** [airgram/airgram#63]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `1.1.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Tdlib/Tdweb has api differences between minor versions, so an exact version of the Airgram must match an exact version of the Tdlib/Tdweb.

**Comment by esindger** [comment]
We create major release for each breaking change in the API. Airgram `2.*` match the `1.5` version of TDLib. Airgram `3.0` will match TDLib `1.6`.

If you found out some errors, please make a report.

**Comment by sh-a-v** [comment]
> Airgram 2.* match the 1.5 version of TDLib
But in the `package.json` TDLib version is `^1.4.3`. 
`1.4.3` has another api and doesn't match Airgram `2.*`.
And if TDLib `1.6.x` will be published, it will break Airgram `2.*`.

`^` matches minor updates (1.x), not patch (1.0.x)

**Comment by esindger** [comment]
Fixed.

**Comment by sh-a-v** [comment]
Thanks!

**Comment by sh-a-v** [comment]
@esindger can you publish new version with fix?

**Comment by esindger** [comment]
Done
