### ISSUE TITLE
Multiply accounts

### ISSUE THREAD

**Issue by kolay-v** [airgram/airgram#64]
**Issue type:**

[ ] question
[ +] bug report
[ +] feature request
[ ] documentation issue

**Airgram version:**

[+ ] `latest`
[ ] `@next`
[ ] `1.1.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Create multiply clients in one node js. It will throw json parsing error, because node-fpi doesn't work with multiply tdlib instances in one process. Is there some functions like https://github.com/Bannerets/tdl/issues/18#issuecomment-429578508
In tdl?

**Comment by esindger** [comment]
Yes, there are. Please check out [documentation](https://airgram.io/api-reference/airgram-instance).
