### ISSUE TITLE
Log verbosity 0 doesn't work

### ISSUE THREAD

**Issue by kolay-v** [airgram/airgram#67]
**Issue type:**

[ ] question
[ x] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[X ] `latest`
[ ] `@next`
[ ] `1.1.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Create airgram object with log verbosity 0. After it tdlib doesn't change log verbosity and output all info llgs

**Comment by esindger** [comment]
Thank you. Will be fixed soon.

**Comment by valoricDe** [comment]
Mornin, I just patched my Airgram.js with `!== undefined` but it is still in any given logLevel much to much stuff. Could you reopen this issue?

**Comment by esindger** [comment]
I will check again.

**Comment by valoricDe** [comment]
Thx 👍 Btw. Do you know I check which version my libtdjson.dylib is? Would it make sense to log the version out at airgram initialization?

**Comment by esindger** [comment]
Last fix is working for me.

Please check if you have something like this in your log:
```
[ 3][t 4][1574858376.474594116][Td10.cpp:164][#1][!Td][&td_requests]    Receive request 1: setLogVerbosityLevel {
  new_verbosity_level = 1
}
```

> Do you know I check which version my libtdjson.dylib is? Would it make sense to log the version out at airgram initialization?

You can see TDLib version in one of the first updates in the log:
```
[ 3][t 4][1574858376.472625017][Td45.cpp:208][#1][!Td][&td_requests]    Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.5.0"
  }
}
```

If your TDLib version is less than 1.4.0, you will fall in [this error](https://github.com/tdlib/td/issues/808).

**Comment by valoricDe** [comment]
Hi, Ok I have version 1.3.0 :hidden_monkey: thanks for pointing out. I updated and now I have a wonderfully clean terminal

**Comment by T1MOXA** [comment]
Hi. 
Can I disable these messages:
![image](https://user-images.githubusercontent.com/19938629/71902683-40676100-316b-11ea-8e88-0819c3902b0f.png)

**Comment by valoricDe** [comment]
Theses are the logs before the verbosity level is set to something. I think it is not possible to get rid of this logs without changing the lib.

**Comment by esindger** [comment]
The first request that Airgram send is `setLogVerbosityLevel` but TDLib at the time has already written some stuff to the log. I tried to start listening updates after sending this request but nothing changing. So I guess it's issue of TDLib.

**Comment by levlam** [comment]
@esindger `setLogVerbosityLevel` is a synchronous method and can be sent through `td_json_client_execute` before a TDLib instance is created. In that case there will be no log entries.

**Comment by esindger** [comment]
Ok, I will implement support of synchronous methods.

**Comment by esindger** [comment]
Done.

**Comment by davidebaldini** [comment]
Airgram 4.0.0 with `logVerbosityLevel` set to 0 still prints debugging info to stderr during start up. I checked the API documentation but I don't understand how to suppress these messages.
