### ISSUE TITLE
How to upload a file?

### ISSUE THREAD

**Issue by wiedymi** [airgram/airgram#70]
How to upload a file from web browser and set it as the avatar for a channel?

**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `1.1.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] question
    [ ] bug report

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by esindger** [comment]
This is a simple example how to upload avatar:

```html
<form id="form">
    <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
    <button type="submit">Upload</button>
</form>
```

```ts
const form = document.getElementById('form') as HTMLFormElement
const fileInput = document.getElementById('avatar') as HTMLInputElement

form.addEventListener('submit', async (e) => {
    e.preventDefault()
    const fileBlob = fileInput.files && fileInput.files.item(0)
    if (fileBlob) {
      // Set your own avatar
      const { response } = await app.airgram.api.setProfilePhoto({
        photo: {
          _: 'inputFileLocal',
          path: fileBlob as any
        }
      })
      console.info(response)
    }
})
```
To set chat avatar you need to use the `setChatPhoto` method:
```ts
const { response } = await app.airgram.api.setChatPhoto({
    chatId: 123,
    photo: {
      _: 'inputFileLocal',
      path: fileBlob as any
    }
})
```

**Comment by morojenoe** [comment]
Hello @esindger,
does it really works?
I haven't tried setChatPhoto, but sendMessage (I've tried audio note) doesn't work with this settings.
The error "Failed to parse JSON object as TDLib request: Expected String, got Object".
```
const params: SendMessageParams = {
  chatId,
  inputMessageContent: {
    _: INPUT_MESSAGE_CONTENT.inputMessageVoiceNote,
    duration: duration,
    voiceNote: {
      _: 'inputFileLocal',
      path: audio as any
    }
  }
};
```

But I've found that tdweb supports one more method 'inputFileBlob', please take a look [here](https://github.com/tdlib/td/blob/d2763fdd5887fc483d0b2bcdda30a6aa564d322a/example/web/tdweb/src/index.js#L22).

And this actually works:
```
const params: SendMessageParams = {
  chatId,
  inputMessageContent: {
    _: INPUT_MESSAGE_CONTENT.inputMessageVoiceNote,
    duration: duration,
    voiceNote: {
      _: 'inputFileBlob',
      data: audio as any
    }
  }
};
```

Could you please check it out?

**Comment by esindger** [comment]
@morojenoe, you're right. Thank you for noticing. Indeed, `tdweb` only suppotrs `inputFileBlob ' input type.
