### ISSUE TITLE
login session not work in browser

### ISSUE THREAD

**Issue by mccoysc** [airgram/airgram#74]
in chrome browser version 78，
the first i use Auth module to login and airgram work well.
then i refresh the web page.
I'll receive some updates:
1,getAuthorizationState
2,updateConnectionState with 'connecting'
3,getAuthorizationState

And after this,no more updates,the airgram not work:no msg would be received,all api would get no response.

**Comment by mccoysc** [comment]
And if i delete all data in browser's indexedDB,refresh the web page,re-login,all is ok.
But if refresh the page without delete data,it don't work again.

**Comment by mccoysc** [comment]
i tested i found that:
at this moment,
1,if i send msg by airgram.api.sendMessage, would get nothing response.
2,if i send msg by airgram.api.send,all is ok.

**Comment by mccoysc** [comment]
i change all calls `airgram.api.getAuthorizationState` to `airgram.provider.send`,the problem is resolved

**Comment by esindger** [comment]
Hello, `Auth` middleware is not intended to work in browsers. It's only for Node.js. You need to implement authorization yourself.

**Comment by mccoysc** [comment]
> Hello, `Auth` middleware is not intended to work in browsers. It's only for Node.js. You need to implement authorization yourself.

i just do the above ，all is ok
