### ISSUE TITLE
Use multiple accounts (Airgram instances) with TdLib

### ISSUE THREAD

**Issue by volodalexey** [airgram/airgram#77]
**Issue type:**

[x] question

**Airgram version:**

[x] `2.3.0`

**TDLib version:**

[x] `1.5.0`

**Steps to reproduce or a small repository showing the problem:**

How can I run Airgram as a bot and Airgram as a user at the same time?
If I use this (the same `apiId` and `apiHash`):
```ts
import { Airgram, Auth } from 'airgram';

const apiId = '...';
const apiHash = '...';
const tdLibPath = '...';

const airgramUser = new Airgram({
  apiId,
  apiHash,
  command: tdLibPath,
  databaseDirectory: '.../userdb',
  logVerbosityLevel: 2,
});

airgramUser.use(
  new Auth({
      phoneNumber: '...',
      code: '...',
  }),
);

const airgramBot = new Airgram({
  apiId,
  apiHash,
  command: tdLibPath,
  databaseDirectory: '.../botdb',
  logVerbosityLevel: 2,
});

airgramBot.use(
  new Auth({
      token: '...'
  }),
);

const userInfo = await airgramUser.api.getMe();
const botInfo = await airgramBot.api.getMe();
```

I get an error:
```bash
[ 0][t 0][1580065911.360865116][Client.cpp:272]	Check `!is_locked` failed
```

I see that this is possible [here](https://github.com/tdlib/td/issues/40)

> One TDLib Client can manage only one account, but there is no limit on number of clients that can be created in one process. So you can create as much TDLib Clients as you want and initialize them with different database and file folders for different accounts.

**Comment by esindger** [comment]
Each Airgram instance [creates](https://github.com/airgram/airgram/blob/master/packages/airgram/src/components/TdProxy.ts#L28) new TDLib client. Perhaps it is not a cause of the error. Have you seen [this issue](https://github.com/tdlib/td/issues/643)?

**Comment by volodalexey** [comment]
I do not know why, but migration to the version `3.02` solved this issue too. Thanks
