### ISSUE TITLE
Airgram destroy() should wait for real TDLib destroy

### ISSUE THREAD

**Issue by volodalexey** [airgram/airgram#78]
**Issue type:**

[x] bug report

**Airgram version:**

[x] `2.3.0`

**Steps to reproduce or a small repository showing the problem:**

I need to correctly destroy Airgram instance for each test:
```ts
describe('Check bot app', () => {
  const airgramBot = new Airgram({
    apiId: '...',
    apiHash: '...',
    command: '...',
    databaseDirectory: '...',
    logVerbosityLevel: 2,
  });

  airgramBot.use(
    new Auth({
      token: '...'
    }),
  );

  beforeAll(async () => {
    const me = await airgramBot.api.getMe();
    expect(me).toBeDefined();
  });

  afterAll(async () => {
    await airgramBot.destroy();
  });
});
```
Wen I run this test with Jest I see following:
```bash
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
I think some long-polling request was not completed.
This might be an [answer](https://github.com/tdlib/td/issues/594#issuecomment-501924145):
> This is a sanity check that td_json_client_receive is not run while the client is being destroyed. td_json_client_destroy completly destroys a client, so the client must not be used from other threads at that time. To properly close the client, you need to call close method and wait for updateAuthorizationState with authorizationStateClosed. After that you can stop to call td_json_client_receive and can destroy the client via td_json_client_destroy.

**Comment by esindger** [comment]
> To properly close the client, you need to call close method and wait for updateAuthorizationState with authorizationStateClosed. After that you can stop to call td_json_client_receive and can destroy the client via td_json_client_destroy.

Done. Please check out last release.

**Comment by volodalexey** [comment]
Awesome. It works! Thanks!
