### ISSUE TITLE
suport tdlib 1.6

### ISSUE THREAD

**Issue by mccoysc** [airgram/airgram#80]
what time to upgrade to tdlib 1.6 and add some new features like qr login and so on

**Comment by mccoysc** [comment]
tdweb is now upgraded to tdlib version 1.6

**Comment by esindger** [comment]
Done!

**Comment by mccoysc** [comment]
> Done!

i suggest you change all the call  `api.getAuthorizationState` to `this.provider.send({method:getAuthorizationState",params: null})`, so that Auth can get work

**Comment by esindger** [comment]
What does not work now? Do you use `Auth` middleware with the `@airgram/web` package? Can you provide your code of the authorization?

**Comment by mccoysc** [comment]
> What does not work now? Do you use `Auth` middleware with the `@airgram/web` package? Can you provide your code of the authorization?

yes,i use Auth in tdweb-airgram.
but the original tdweb-airgram would hang if you use Auth.

so i change all calls using api.getAuthorizationState to this.provider.send({method:getAuthorizationState",params: null}), and then all is workwell

**Comment by mccoysc** [comment]
i can't compile the source code in airgram-web by webpack,so i use npm pkg "tdweb-airgram".
is it yours?

**Comment by esindger** [comment]
> i can't compile the source code in airgram-web by webpack,so i use npm pkg "tdweb-airgram" instead.

It's very old package, you should use `@airgram/web`.

**Comment by mccoysc** [comment]
> > i can't compile the source code in airgram-web by webpack,so i use npm pkg "tdweb-airgram" instead.
> 
> It's very old package, you should use `@airgram/web`.

and another question:
the "CHANGE" can make Auth work,yes?

**Comment by esindger** [comment]
Auth middleware is supposed to work in Node.js. If you can provide an example how you want to use it with browser, I will check what possible to do.

**Comment by mccoysc** [comment]
just used like using way in node

**Comment by esindger** [comment]
> and i found you comment some functions like "addProxy" and so on.

Unfortunately, tdweb does [not support](https://github.com/tdlib/td/issues/729) proxy.

**Comment by mccoysc** [comment]
[https://sp-public-web.ecspool.com/test.html](https://sp-public-web.ecspool.com/test.html)

you can check the code in the above url though `F12`

**Comment by esindger** [comment]
Okay, thank you for the example.

**Comment by mccoysc** [comment]
> > and i found you comment some functions like "addProxy" and so on.
> 
> Unfortunately, tdweb does [not support](https://github.com/tdlib/td/issues/729) proxy.

tdweb comment some functions like "addProxy".
i make some change to get the functions work.
you can have a try in the above url.

**Comment by esindger** [comment]
Please check out the [example](https://github.com/airgram/airgram/blob/master/examples/webpack-config/src/App.ts) of using Auth middleware with browser.

**Comment by mccoysc** [comment]
> Please check out the [example](https://github.com/airgram/airgram/blob/master/examples/webpack-config/src/App.ts) of using Auth middleware with browser.

you made the changes?

**Comment by esindger** [comment]
>tdweb comment some functions like "addProxy".
> i make some change to get the functions work.
> you can have a try in the above url.

If it works, that's nice. So you can use proxy.

> you made the changes?

Yes.

**Comment by mccoysc** [comment]
> > tdweb comment some functions like "addProxy".
> > i make some change to get the functions work.
> > you can have a try in the above url.
> 
> If it works, that's nice. So you can use proxy.
> 
> > you made the changes?
> 
> Yes.

also ,pls release and upgrade the npm pkg for airgram and airgram/web

**Comment by esindger** [comment]
It has already been updated.

**Comment by mccoysc** [comment]
i found it's still keep 3.0.1 in npm and ,
only airgram/web keep 3.0.1 in github release

**Comment by esindger** [comment]
No, all the last versions has released as npm packages.
