### ISSUE TITLE
Channel data gathering

### ISSUE THREAD

**Issue by skakodube** [airgram/airgram#83]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

So, I need to gather some general statistics and the amount of members from a channel by its URL(or sth similar), being not an admin of it. Is it possible to manage this with your library?
I've read the whole documentation and I could't find anything similar to what I'm taking about and what I've found in original telegram API :

- https://core.telegram.org/method/messages.getStatsURL
- https://core.telegram.org/method/channels.getParticipants

If it is, could you give me any hints how can I achieve this?

**Comment by esindger** [comment]
Hello,
Please check out the TDLib analogs of the methods you mentioned: [getChatStatisticsUrl](https://airgram.io/api-reference/api-methods/getChatStatisticsUrl), [getSupergroupMembers](https://airgram.io/api-reference/api-methods/getSupergroupMembers)
