### ISSUE TITLE
Does it work with React Native?

### ISSUE THREAD

**Issue by ChristoRibeiro** [airgram/airgram#86]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[X] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm getting some issues with React Native. Do you know if Airgram has been thinking to work with React Native? Or just for the mobile?

```js
The package at "node_modules/airgram/components/TdProxy.js" attempted to import the Node standard library module "path". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
Failed building JavaScript bundle.
```

**Comment by esindger** [comment]
Sorry for the late reply. Airgram was not designed for using with React Native. However, everything should work properly, if you replace the Node standard library dependencies to third party packages. Pull request is welcome.

**Comment by ChristoRibeiro** [comment]
Thanks for your reply. I'll take a look and make a PR.

**Comment by gaithoben** [comment]
Did anyone to manage to make Airgram work on a RN project>
