### ISSUE TITLE
[sendMessage] Chat not found

### ISSUE THREAD

**Issue by jumoog** [airgram/airgram#88]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[x] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Im trying to send messages to private channel. My bot is Admin.
Sometimes im getting.

> [sendMessage][5] Chat not found

I checked the issues related to that topic and added 

```
void (async function () {
  const { response: chats } = await airgram.api.getChats({
    limit: 10,
    offsetChatId: 0,
    offsetOrder: '9223372036854775807'
  })
  console.log('[My chats] ', chats)
})()
```

When i start the Client im getting:

> [My chats]  {
>   _: 'error',
>   code: 400,
>   message: 'The method is not available for bots'
> }

Whats the Problem? 
I noticed that when I write a message in the channel, sendMessage works the next time.

**Comment by jumoog** [comment]
i switched to user auth and now everything works

**Comment by esindger** [comment]
Please check out #53 and https://github.com/tdlib/td/issues/837.

**Comment by jumoog** [comment]
Where is the Repo for the API docu? I'll do a pull request that would mention at the function getChats that this function does not work for bots and you have to use getChat instead.

**Comment by esindger** [comment]
The source of the documentstion is here: https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl

**Comment by piavgh** [comment]
I still don't know why I need to add this piece of code in order to make it works:

```
void (async function () {

  // ----------- Without this code, it doesn't work
  const { response: chats } = await airgram.api.getChats({
    limit: 10,
    offsetChatId: 0,
    offsetOrder: '9223372036854775807',
  });
  console.log('[My chats] ', chats);
  // -----------


  const req = await fetch(giphyURL);
  const res = await req.json();
  console.log('res', res.data.images.original.url);

  const { response } = await airgram.api.sendMessage({
    chatId: <My group ID here>,
    inputMessageContent: {
      _: 'inputMessageText',
      text: {
        text: res.data.images.original.url,
      },
    },
  });

  console.log('response = ', response);
})();
```

**Comment by jumoog** [comment]
`TDLib` doesn't know any Chat/Group IDs. To get your IDs you have to call `getChats`
