### ISSUE TITLE
Is persistent store transferable to another project?

### ISSUE THREAD

**Issue by volodalexey** [airgram/airgram#9]
With my simple JSON store I performed authorization in one project. In JSON store (`store.json`) I have:
```
{
  "airgram:auth": {
    "phoneNumber": "...",
    "isRegistered": true,
    "phoneCodeHash": "...",
    "waitUntil": ...,
    "code": "...",
    "userId": ...
  },
  "airgram:mtp": {
    "dc2.authKey": "...",
    "dc2.serverSalt": "..."
  }
}
```
And inside this project I am able to send requests.
However if I want to use the same "authorization" for another project I copy (`store.json`) to another project. And any request from another project fails. I always get:
```
console.error node_modules/airgram/base/Logger.js:105
    [1] sendScheduledRequest() rpcError {
      "name": "RpcError",
      "type": "NETWORK_BAD_RESPONSE",
      "code": 406,
      "message": "CODE#406 NETWORK_BAD_RESPONSE",
      "url": "http://149.154.167.51:443/apiw1",
      "stack": "CODE#406 NETWORK_BAD_RESPONSE\n    at .../node_modules/src/base/MtpClient.ts:645:18\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"
    }
```
Is it possible to use the same authorization from another project (definitely not at the same time).
I assume that each `airgram` library generates its own `unique key`, however: why this key is not stored (or where can I find this key)?

**Comment by airgram** [comment]
You may use the same authorization.

> I assume that each airgram library generates its own unique key

Airgram doesn't generate secret key automatically. User have to set it manually: 

```
import { generateSecretKeys } from 'airgram/helpers'

...

// You have to generate secret keys only once and keep them separate
// const secret = generateSecretKeys()
airgram.client.crypto.setSecretKeys(secret)
airgram.client.mtpState.encryptedFields = true
```

So if you initialize projects with the same settings, authorization should work. Try to call `await airgram.client.mtpState.get()` and compare the result on both projects. It should be the same.

**Comment by volodalexey** [comment]
Again forgot to use jest [settings](https://github.com/airgram/airgram/issues/5).
