### ISSUE TITLE
Statically linking openssl

### ISSUE THREAD

**Issue by KhushrajRathod** [airgram/airgram#90]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ ] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

I've built TDlib for macOS using the build instructions generator as specified in the readme. The library works on my machine, but when trying to use it on a device without openssl installed, I get a dynamic linking error. How can I link openssl statically? I'm building an electron application with nodejs.
Thanks

**Comment by esindger** [comment]
Hello,
I would suggest you to ask this question in the [TDLib repository](https://github.com/tdlib/td).
