### ISSUE TITLE
Unknown class "addContact"

### ISSUE THREAD

**Issue by oktaysenkan** [airgram/airgram#94]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ ] `latest`
[ ] `@next`
[x] `3.0.1` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```ts
const addContact = async (user: User) => {
  console.log(user);

  const { response } = await airgram.api.addContact({
    contact: {
      _: "contact",
      firstName: user.firstName,
      lastName: user.lastName,
      phoneNumber: user.phoneNumber,
      userId: user.id,
      vcard: "deneme",
    },
    sharePhoneNumber: true,
  });

  if (response._ === "error") {
    return Promise.reject(response.message);
  }

  return Promise.resolve(response);
};
```

Its rejects `Failed to parse JSON object as TDLib request: Unknown class "addContact"`

**Comment by esindger** [comment]
Your TDLib version is old. The `addContact` method is only supported since version 1.6.0.

**Comment by oktaysenkan** [comment]
I am already using 1.6

**Comment by esindger** [comment]
Thank you for the pull request! I've merged it.
