### ISSUE TITLE
sendMessage returns canBeEdited:false always

### ISSUE THREAD

**Issue by eringiso** [airgram/airgram#97]
**Issue type:**

[x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Airgram version:**

[ x] `latest`
[ ] `@next`
[ ] `2.3.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
how to edit the sent message i'm trying to update the msg 

    const {sendMessage} = await airgram.api.sendMessage({
        chatId: cId,
        replyToMessageId: 0,
        canBeEdited:true,
        disableNotification: false,
        fromBackground: false,
        inputMessageContent: {
          _: "inputMessageText",
          text: {
            text: "my text"
          }
        }
      });

i get the response as
     {
	  _: 'message',
	  id: id,
	  senderUserId: id,
	  chatId: id,
	  sendingState: { _: 'messageSendingStatePending' },
	  isOutgoing: true,
	  canBeEdited: false,
	  canBeForwarded: true,
	  canBeDeletedOnlyForSelf: true,
	  canBeDeletedForAllUsers: false,
	  isChannelPost: false,
	  containsUnreadMention: false,
	  date: 1234567,
	  editDate: 0,
	  replyToMessageId: 0,
	  ttl: 0,
	  ttlExpiresIn: 0,
	  viaBotUserId: 0,
	  authorSignature: '',
	  views: 0,
	  mediaAlbumId: '0',
	  restrictionReason: '',
	  content: {
	    _: 'messageText',
	    text: {
	      _: 'formattedText',
	      text: 'my text',
	      entities: []
	    }
	  }
	}

	even though i set canBeEdited to true it returns as false
 

  const {editMessage} = await airgram.api.editMessageText({
        chatId: cId,
        messageId: mId,
        inputMessageContent: {
          _: "inputMessageText",
          text: {
            text: "Edited text"
          }
        }
      })

      console.log(editMessage);

i get the response as 

{
  _: 'editMessageText',
  airgram: [Getter],
  state: [Getter],
  request: [Getter],
  response: { _: 'error', code: 5, message: "Message can't be edited" }
}
(node:5478) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'editMessage' of '(intermediate value)' as it is undefined.

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] question
    [ ] bug report

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by eringiso** [comment]
found the solution we can't edit the message because the id we get from the response is temporary
which will change once it's delivered so you have to get the new msg id from updateMessageSendSucceeded
like this


      airgram.on("updateMessageSendSucceeded", async ({
        update
      }) => {
        console.log(update));

        const {message} = update

        console.log(message.id);

      })

**Comment by jagzmz** [comment]
> found the solution we can't edit the message because the id we get from the response is temporary
> which will change once it's delivered so you have to get the new msg id from updateMessageSendSucceeded 
@eringiso 
How are you keeping map between temporary message id and new message id which comes in updateMessageSendSucceeded

**Comment by eringiso** [comment]
@jagzmz 
you can look at this helper function https://github.com/airgram/airgram/issues/99#issuecomment-629559071
