### ISSUE TITLE
method getChatHistory

### ISSUE THREAD

**Issue by mitGen** [airgram/airgram#98]
**Issue type:**
Hello!!!!!
Why methid "getChatHistory" return only the last message if there are a lot of them in the chat????
REQUEST:
![image](https://user-images.githubusercontent.com/44039203/81512867-c28bb000-932c-11ea-8d65-337ad280abdb.png)
RESPONSE:
![image](https://user-images.githubusercontent.com/44039203/81512880-e222d880-932c-11ea-9fbb-b31d0c302ff7.png)

**Airgram version:**

[ ] `latest`
[ ] `@next`
[ ] `3.0.2` (or put your version here)

**Comment by esindger** [comment]
Hello, 
Please check out [this issue](https://github.com/airgram/airgram/issues/53).

**Comment by mitGen** [comment]
Thanks, everything works fine))))
